.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.39.3 */

nonmatching D_80080160_ovl2, 0x4

dlabel D_80080160_ovl2
    /* 80080160 */ .space 0x04

nonmatching D_80080164_ovl2, 0xC

dlabel D_80080164_ovl2
    /* 80080164 */ .space 0x0C

nonmatching D_80080170_ovl2, 0x4

dlabel D_80080170_ovl2
    /* 80080170 */ .space 0x04

nonmatching D_80080174_ovl2, 0xC

dlabel D_80080174_ovl2
    /* 80080174 */ .space 0x0C

nonmatching D_80080180_ovl2, 0x2

dlabel D_80080180_ovl2
    /* 80080180 */ .space 0x02

nonmatching D_80080182_ovl2, 0x2

dlabel D_80080182_ovl2
    /* 80080182 */ .space 0x02

nonmatching D_80080184_ovl2, 0x1

dlabel D_80080184_ovl2
    /* 80080184 */ .space 0x01

nonmatching D_80080185_ovl2, 0x1

dlabel D_80080185_ovl2
    /* 80080185 */ .space 0x01

nonmatching D_80080186_ovl2, 0x2

dlabel D_80080186_ovl2
    /* 80080186 */ .space 0x02

nonmatching D_80080188_ovl2, 0x2

dlabel D_80080188_ovl2
    /* 80080188 */ .space 0x02

nonmatching D_8008018A_ovl2, 0x2

dlabel D_8008018A_ovl2
    /* 8008018A */ .space 0x02

nonmatching D_8008018C_ovl2, 0x4

dlabel D_8008018C_ovl2
    /* 8008018C */ .space 0x04

nonmatching D_80080190_ovl2, 0x4

dlabel D_80080190_ovl2
    /* 80080190 */ .space 0x04

nonmatching D_80080194_ovl2, 0x4

dlabel D_80080194_ovl2
    /* 80080194 */ .space 0x04

nonmatching D_80080198_ovl2, 0x4

dlabel D_80080198_ovl2
    /* 80080198 */ .space 0x04

nonmatching D_8008019C_ovl2, 0x4

dlabel D_8008019C_ovl2
    /* 8008019C */ .space 0x04

nonmatching D_800801A0_ovl2, 0x1

dlabel D_800801A0_ovl2
    /* 800801A0 */ .space 0x01

nonmatching D_800801A1_ovl2, 0x1

dlabel D_800801A1_ovl2
    /* 800801A1 */ .space 0x01

nonmatching D_800801A2_ovl2, 0x46

dlabel D_800801A2_ovl2
    /* 800801A2 */ .space 0x46

nonmatching D_800801E8_ovl2, 0x4

dlabel D_800801E8_ovl2
    /* 800801E8 */ .space 0x04

nonmatching D_800801EC_ovl2, 0x4

dlabel D_800801EC_ovl2
    /* 800801EC */ .space 0x04

nonmatching D_800801F0_ovl2, 0x4

dlabel D_800801F0_ovl2
    /* 800801F0 */ .space 0x04

nonmatching D_800801F4_ovl2, 0x4

dlabel D_800801F4_ovl2
    /* 800801F4 */ .space 0x04

nonmatching D_800801F8_ovl2, 0x8

dlabel D_800801F8_ovl2
    /* 800801F8 */ .space 0x08

nonmatching D_80080200_ovl2, 0x4

dlabel D_80080200_ovl2
    /* 80080200 */ .space 0x04

nonmatching D_80080204_ovl2, 0x4

dlabel D_80080204_ovl2
    /* 80080204 */ .space 0x04

nonmatching D_80080208_ovl2, 0x8

dlabel D_80080208_ovl2
    /* 80080208 */ .space 0x08

nonmatching D_80080210_ovl2, 0x10

dlabel D_80080210_ovl2
    /* 80080210 */ .space 0x10

nonmatching D_80080220_ovl2, 0x20

dlabel D_80080220_ovl2
    /* 80080220 */ .space 0x20

nonmatching D_80080240_ovl2, 0x1

dlabel D_80080240_ovl2
    /* 80080240 */ .space 0x01

nonmatching D_80080241_ovl2, 0x1

dlabel D_80080241_ovl2
    /* 80080241 */ .space 0x01

nonmatching D_80080242_ovl2, 0x1

dlabel D_80080242_ovl2
    /* 80080242 */ .space 0x01

nonmatching D_80080243_ovl2, 0x1

dlabel D_80080243_ovl2
    /* 80080243 */ .space 0x01

nonmatching D_80080244_ovl2, 0x2

dlabel D_80080244_ovl2
    /* 80080244 */ .space 0x02

nonmatching D_80080246_ovl2, 0x2

dlabel D_80080246_ovl2
    /* 80080246 */ .space 0x02

nonmatching D_80080248_ovl2, 0x8

dlabel D_80080248_ovl2
    /* 80080248 */ .space 0x08

nonmatching D_80080250_ovl2, 0x8

dlabel D_80080250_ovl2
    /* 80080250 */ .space 0x08

nonmatching D_80080258_ovl2, 0x4

dlabel D_80080258_ovl2
    /* 80080258 */ .space 0x04

nonmatching D_8008025C_ovl2, 0x4

dlabel D_8008025C_ovl2
    /* 8008025C */ .space 0x04

nonmatching D_80080260_ovl2, 0x1

dlabel D_80080260_ovl2
    /* 80080260 */ .space 0x01

nonmatching D_80080261_ovl2, 0x1

dlabel D_80080261_ovl2
    /* 80080261 */ .space 0x01

nonmatching D_80080262_ovl2, 0x1

dlabel D_80080262_ovl2
    /* 80080262 */ .space 0x01

nonmatching D_80080263_ovl2, 0x1

dlabel D_80080263_ovl2
    /* 80080263 */ .space 0x01

nonmatching D_80080264_ovl2, 0x2

dlabel D_80080264_ovl2
    /* 80080264 */ .space 0x02

nonmatching D_80080266_ovl2, 0xA

dlabel D_80080266_ovl2
    /* 80080266 */ .space 0x0A

nonmatching D_80080270_ovl2, 0x10

dlabel D_80080270_ovl2
    /* 80080270 */ .space 0x10

nonmatching D_80080280_ovl2, 0x10

dlabel D_80080280_ovl2
    /* 80080280 */ .space 0x10

nonmatching D_80080290_ovl2, 0x4

dlabel D_80080290_ovl2
    /* 80080290 */ .space 0x04

nonmatching D_80080294_ovl2, 0x4

dlabel D_80080294_ovl2
    /* 80080294 */ .space 0x04

nonmatching D_80080298_ovl2, 0x4

dlabel D_80080298_ovl2
    /* 80080298 */ .space 0x04

nonmatching D_8008029C_ovl2, 0x4

dlabel D_8008029C_ovl2
    /* 8008029C */ .space 0x04

nonmatching D_800802A0_ovl2, 0x4

dlabel D_800802A0_ovl2
    /* 800802A0 */ .space 0x04

nonmatching D_800802A4_ovl2, 0xC

dlabel D_800802A4_ovl2
    /* 800802A4 */ .space 0x0C

nonmatching D_800802B0_ovl2, 0x1

dlabel D_800802B0_ovl2
    /* 800802B0 */ .space 0x01

nonmatching D_800802B1_ovl2, 0x1

dlabel D_800802B1_ovl2
    /* 800802B1 */ .space 0x01

nonmatching D_800802B2_ovl2, 0x2

dlabel D_800802B2_ovl2
    /* 800802B2 */ .space 0x02

nonmatching D_800802B4_ovl2, 0xC

dlabel D_800802B4_ovl2
    /* 800802B4 */ .space 0x0C

nonmatching D_800802C0_ovl2, 0x4

dlabel D_800802C0_ovl2
    /* 800802C0 */ .space 0x04

nonmatching D_800802C4_ovl2, 0x4

dlabel D_800802C4_ovl2
    /* 800802C4 */ .space 0x04

nonmatching D_800802C8_ovl2, 0x8

dlabel D_800802C8_ovl2
    /* 800802C8 */ .space 0x08

nonmatching D_800802D0_ovl2, 0x4

dlabel D_800802D0_ovl2
    /* 800802D0 */ .space 0x04

nonmatching D_800802D4_ovl2, 0x4

dlabel D_800802D4_ovl2
    /* 800802D4 */ .space 0x04

nonmatching D_800802D8_ovl2, 0x4

dlabel D_800802D8_ovl2
    /* 800802D8 */ .space 0x04

nonmatching D_800802DC_ovl2, 0x3

dlabel D_800802DC_ovl2
    /* 800802DC */ .space 0x03

nonmatching D_800802DF_ovl2, 0x1

dlabel D_800802DF_ovl2
    /* 800802DF */ .space 0x01

nonmatching D_800802E0_ovl2, 0x4

dlabel D_800802E0_ovl2
    /* 800802E0 */ .space 0x04

nonmatching D_800802E4_ovl2, 0x4

dlabel D_800802E4_ovl2
    /* 800802E4 */ .space 0x04

nonmatching D_800802E8_ovl2, 0x4

dlabel D_800802E8_ovl2
    /* 800802E8 */ .space 0x04

nonmatching D_800802EC_ovl2, 0x4

dlabel D_800802EC_ovl2
    /* 800802EC */ .space 0x04

nonmatching D_800802F0_ovl2, 0x3

dlabel D_800802F0_ovl2
    /* 800802F0 */ .space 0x03

nonmatching D_800802F3_ovl2, 0x1

dlabel D_800802F3_ovl2
    /* 800802F3 */ .space 0x01

nonmatching D_800802F4_ovl2, 0x4

dlabel D_800802F4_ovl2
    /* 800802F4 */ .space 0x04

nonmatching D_800802F8_ovl2, 0x4

dlabel D_800802F8_ovl2
    /* 800802F8 */ .space 0x04

nonmatching D_800802FC_ovl2, 0x4

dlabel D_800802FC_ovl2
    /* 800802FC */ .space 0x04

nonmatching D_80080300_ovl2, 0x4

dlabel D_80080300_ovl2
    /* 80080300 */ .space 0x04

nonmatching D_80080304_ovl2, 0x4

dlabel D_80080304_ovl2
    /* 80080304 */ .space 0x04

nonmatching D_80080308_ovl2, 0x4

dlabel D_80080308_ovl2
    /* 80080308 */ .space 0x04

nonmatching D_8008030C_ovl2, 0x4

dlabel D_8008030C_ovl2
    /* 8008030C */ .space 0x04

nonmatching D_80080310_ovl2, 0x4

dlabel D_80080310_ovl2
    /* 80080310 */ .space 0x04

nonmatching D_80080314_ovl2, 0x4

dlabel D_80080314_ovl2
    /* 80080314 */ .space 0x04

nonmatching D_80080318_ovl2, 0x3

dlabel D_80080318_ovl2
    /* 80080318 */ .space 0x03

nonmatching D_8008031B_ovl2, 0x1

dlabel D_8008031B_ovl2
    /* 8008031B */ .space 0x01

nonmatching D_8008031C_ovl2, 0x3

dlabel D_8008031C_ovl2
    /* 8008031C */ .space 0x03

nonmatching D_8008031F_ovl2, 0x1

dlabel D_8008031F_ovl2
    /* 8008031F */ .space 0x01

nonmatching D_80080320_ovl2, 0x3

dlabel D_80080320_ovl2
    /* 80080320 */ .space 0x03

nonmatching D_80080323_ovl2, 0x1

dlabel D_80080323_ovl2
    /* 80080323 */ .space 0x01

nonmatching D_80080324_ovl2, 0xC

dlabel D_80080324_ovl2
    /* 80080324 */ .space 0x0C

nonmatching D_80080330_ovl2, 0x4

dlabel D_80080330_ovl2
    /* 80080330 */ .space 0x04

nonmatching D_80080334_ovl2, 0x4

dlabel D_80080334_ovl2
    /* 80080334 */ .space 0x04

nonmatching D_80080338_ovl2, 0x40

dlabel D_80080338_ovl2
    /* 80080338 */ .space 0x40

nonmatching D_80080378_ovl2, 0x240

dlabel D_80080378_ovl2
    /* 80080378 */ .space 0x240

nonmatching D_800805B8_ovl2, 0x4

dlabel D_800805B8_ovl2
    /* 800805B8 */ .space 0x04

nonmatching D_800805BC_ovl2, 0x4

dlabel D_800805BC_ovl2
    /* 800805BC */ .space 0x04

nonmatching D_800805C0_ovl2, 0x4

dlabel D_800805C0_ovl2
    /* 800805C0 */ .space 0x04

nonmatching D_800805C4_ovl2, 0xC

dlabel D_800805C4_ovl2
    /* 800805C4 */ .space 0x0C

nonmatching D_800805D0_ovl2, 0x10

dlabel D_800805D0_ovl2
    /* 800805D0 */ .space 0x10

nonmatching D_800805E0_ovl2, 0x4

dlabel D_800805E0_ovl2
    /* 800805E0 */ .space 0x04

nonmatching D_800805E4_ovl2, 0x44

dlabel D_800805E4_ovl2
    /* 800805E4 */ .space 0x44

nonmatching D_80080628_ovl2, 0x4

dlabel D_80080628_ovl2
    /* 80080628 */ .space 0x04

nonmatching D_8008062C_ovl2, 0x4

dlabel D_8008062C_ovl2
    /* 8008062C */ .space 0x04

nonmatching D_80080630_ovl2, 0x4

dlabel D_80080630_ovl2
    /* 80080630 */ .space 0x04

nonmatching D_80080634_ovl2, 0x1

dlabel D_80080634_ovl2
    /* 80080634 */ .space 0x01

nonmatching D_80080635_ovl2, 0x1

dlabel D_80080635_ovl2
    /* 80080635 */ .space 0x01

nonmatching D_80080636_ovl2, 0x2

dlabel D_80080636_ovl2
    /* 80080636 */ .space 0x02

nonmatching D_80080638_ovl2, 0x8

dlabel D_80080638_ovl2
    /* 80080638 */ .space 0x08

nonmatching D_80080640_ovl2, 0x4

dlabel D_80080640_ovl2
    /* 80080640 */ .space 0x04

nonmatching D_80080644_ovl2, 0x4

dlabel D_80080644_ovl2
    /* 80080644 */ .space 0x04

nonmatching D_80080648_ovl2, 0x40

dlabel D_80080648_ovl2
    /* 80080648 */ .space 0x40

nonmatching D_80080688_ovl2, 0x4

dlabel D_80080688_ovl2
    /* 80080688 */ .space 0x04

nonmatching D_8008068C_ovl2, 0x4

dlabel D_8008068C_ovl2
    /* 8008068C */ .space 0x04

nonmatching D_80080690_ovl2, 0x4

dlabel D_80080690_ovl2
    /* 80080690 */ .space 0x04

nonmatching D_80080694_ovl2, 0x4

dlabel D_80080694_ovl2
    /* 80080694 */ .space 0x04

nonmatching D_80080698_ovl2, 0x4

dlabel D_80080698_ovl2
    /* 80080698 */ .space 0x04

nonmatching D_8008069C_ovl2, 0x64

dlabel D_8008069C_ovl2
    /* 8008069C */ .space 0x64

nonmatching D_80080700_ovl2, 0x2

dlabel D_80080700_ovl2
    /* 80080700 */ .space 0x02

nonmatching D_80080702_ovl2, 0x6

dlabel D_80080702_ovl2
    /* 80080702 */ .space 0x06

nonmatching D_80080708_ovl2, 0x20

dlabel D_80080708_ovl2
    /* 80080708 */ .space 0x20

nonmatching D_80080728_ovl2, 0x4

dlabel D_80080728_ovl2
    /* 80080728 */ .space 0x04

nonmatching D_8008072C_ovl2, 0x4

dlabel D_8008072C_ovl2
    /* 8008072C */ .space 0x04

nonmatching D_80080730_ovl2, 0x4

dlabel D_80080730_ovl2
    /* 80080730 */ .space 0x04

nonmatching D_80080734_ovl2, 0x4

dlabel D_80080734_ovl2
    /* 80080734 */ .space 0x04

nonmatching D_80080738_ovl2, 0x8

dlabel D_80080738_ovl2
    /* 80080738 */ .space 0x08

nonmatching D_80080740_ovl2, 0x4

dlabel D_80080740_ovl2
    /* 80080740 */ .space 0x04

nonmatching D_80080744_ovl2, 0xC

dlabel D_80080744_ovl2
    /* 80080744 */ .space 0x0C

nonmatching D_80080750_ovl2, 0x1

dlabel D_80080750_ovl2
    /* 80080750 */ .space 0x01

nonmatching D_80080751_ovl2, 0x3

dlabel D_80080751_ovl2
    /* 80080751 */ .space 0x03

nonmatching D_80080754_ovl2, 0x4

dlabel D_80080754_ovl2
    /* 80080754 */ .space 0x04

nonmatching D_80080758_ovl2, 0x4

dlabel D_80080758_ovl2
    /* 80080758 */ .space 0x04

nonmatching D_8008075C_ovl2, 0x2B8

dlabel D_8008075C_ovl2
    /* 8008075C */ .space 0x2B8

nonmatching D_80080A14_ovl2, 0x1184

dlabel D_80080A14_ovl2
    /* 80080A14 */ .space 0x1184

nonmatching D_80081B98_ovl2, 0x8

dlabel D_80081B98_ovl2
    /* 80081B98 */ .space 0x08

nonmatching D_80081BA0_ovl2, 0x70

dlabel D_80081BA0_ovl2
    /* 80081BA0 */ .space 0x70

nonmatching D_80081C10_ovl2, 0x13E0

dlabel D_80081C10_ovl2
    /* 80081C10 */ .space 0x13E0

nonmatching D_80082FF0_ovl2, 0x4

dlabel D_80082FF0_ovl2
    /* 80082FF0 */ .space 0x04

nonmatching D_80082FF4_ovl2, 0x1

dlabel D_80082FF4_ovl2
    /* 80082FF4 */ .space 0x01

nonmatching D_80082FF5_ovl2, 0x3

dlabel D_80082FF5_ovl2
    /* 80082FF5 */ .space 0x03

nonmatching D_80082FF8_ovl2, 0x4

dlabel D_80082FF8_ovl2
    /* 80082FF8 */ .space 0x04

nonmatching D_80082FFC_ovl2, 0x4

dlabel D_80082FFC_ovl2
    /* 80082FFC */ .space 0x04

nonmatching D_80083000_ovl2, 0x4

dlabel D_80083000_ovl2
    /* 80083000 */ .space 0x04

nonmatching D_80083004_ovl2, 0x4

dlabel D_80083004_ovl2
    /* 80083004 */ .space 0x04

nonmatching D_80083008_ovl2, 0x4

dlabel D_80083008_ovl2
    /* 80083008 */ .space 0x04

nonmatching D_8008300C_ovl2, 0x4

dlabel D_8008300C_ovl2
    /* 8008300C */ .space 0x04

nonmatching D_80083010_ovl2, 0x4

dlabel D_80083010_ovl2
    /* 80083010 */ .space 0x04

nonmatching D_80083014_ovl2, 0x4

dlabel D_80083014_ovl2
    /* 80083014 */ .space 0x04

nonmatching D_80083018_ovl2, 0x8

dlabel D_80083018_ovl2
    /* 80083018 */ .space 0x08

nonmatching D_80083020_ovl2, 0xE8

dlabel D_80083020_ovl2
    /* 80083020 */ .space 0xE8

nonmatching D_80083108_ovl2, 0x20

dlabel D_80083108_ovl2
    /* 80083108 */ .space 0x20

nonmatching D_80083128_ovl2, 0x8

dlabel D_80083128_ovl2
    /* 80083128 */ .space 0x08

nonmatching D_80083130_ovl2, 0x8F0

dlabel D_80083130_ovl2
    /* 80083130 */ .space 0x8F0

nonmatching D_80083A20_ovl2, 0x1

dlabel D_80083A20_ovl2
    /* 80083A20 */ .space 0x01

nonmatching D_80083A21_ovl2, 0x3

dlabel D_80083A21_ovl2
    /* 80083A21 */ .space 0x03

nonmatching D_80083A24_ovl2, 0x2

dlabel D_80083A24_ovl2
    /* 80083A24 */ .space 0x02

nonmatching D_80083A26_ovl2, 0x2

dlabel D_80083A26_ovl2
    /* 80083A26 */ .space 0x02

nonmatching D_80083A28_ovl2, 0x4

dlabel D_80083A28_ovl2
    /* 80083A28 */ .space 0x04

nonmatching D_80083A2C_ovl2, 0x4

dlabel D_80083A2C_ovl2
    /* 80083A2C */ .space 0x04

nonmatching D_80083A30_ovl2, 0x4

dlabel D_80083A30_ovl2
    /* 80083A30 */ .space 0x04

nonmatching D_80083A34_ovl2, 0x8

dlabel D_80083A34_ovl2
    /* 80083A34 */ .space 0x08

nonmatching D_80083A3C_ovl2, 0x4

dlabel D_80083A3C_ovl2
    /* 80083A3C */ .space 0x04

nonmatching D_80083A40_ovl2, 0x790

dlabel D_80083A40_ovl2
    /* 80083A40 */ .space 0x790

nonmatching D_800841D0_ovl2, 0x10

dlabel D_800841D0_ovl2
    /* 800841D0 */ .space 0x10

nonmatching D_800841E0_ovl2, 0x4

dlabel D_800841E0_ovl2
    /* 800841E0 */ .space 0x04

nonmatching D_800841E4_ovl2, 0x4

dlabel D_800841E4_ovl2
    /* 800841E4 */ .space 0x04

nonmatching D_800841E8_ovl2, 0x4

dlabel D_800841E8_ovl2
    /* 800841E8 */ .space 0x04

nonmatching D_800841EC_ovl2, 0x4

dlabel D_800841EC_ovl2
    /* 800841EC */ .space 0x04

nonmatching D_800841F0_ovl2, 0x4

dlabel D_800841F0_ovl2
    /* 800841F0 */ .space 0x04

nonmatching D_800841F4_ovl2, 0x4

dlabel D_800841F4_ovl2
    /* 800841F4 */ .space 0x04

nonmatching D_800841F8_ovl2, 0x4

dlabel D_800841F8_ovl2
    /* 800841F8 */ .space 0x04

nonmatching D_800841FC_ovl2, 0x4

dlabel D_800841FC_ovl2
    /* 800841FC */ .space 0x04

nonmatching D_80084200_ovl2, 0x4

dlabel D_80084200_ovl2
    /* 80084200 */ .space 0x04

nonmatching D_80084204_ovl2, 0x4

dlabel D_80084204_ovl2
    /* 80084204 */ .space 0x04

nonmatching D_80084208_ovl2, 0x4

dlabel D_80084208_ovl2
    /* 80084208 */ .space 0x04

nonmatching D_8008420C_ovl2, 0x4

dlabel D_8008420C_ovl2
    /* 8008420C */ .space 0x04

nonmatching D_80084210_ovl2, 0x4

dlabel D_80084210_ovl2
    /* 80084210 */ .space 0x04

nonmatching D_80084214_ovl2, 0x4

dlabel D_80084214_ovl2
    /* 80084214 */ .space 0x04

nonmatching D_80084218_ovl2, 0x4

dlabel D_80084218_ovl2
    /* 80084218 */ .space 0x04

nonmatching D_8008421C_ovl2, 0x4

dlabel D_8008421C_ovl2
    /* 8008421C */ .space 0x04

nonmatching D_80084220_ovl2, 0x4

dlabel D_80084220_ovl2
    /* 80084220 */ .space 0x04

nonmatching D_80084224_ovl2, 0x4

dlabel D_80084224_ovl2
    /* 80084224 */ .space 0x04

nonmatching D_80084228_ovl2, 0x4

dlabel D_80084228_ovl2
    /* 80084228 */ .space 0x04

nonmatching D_8008422C_ovl2, 0x4

dlabel D_8008422C_ovl2
    /* 8008422C */ .space 0x04

nonmatching D_80084230_ovl2, 0x4

dlabel D_80084230_ovl2
    /* 80084230 */ .space 0x04

nonmatching D_80084234_ovl2, 0x4

dlabel D_80084234_ovl2
    /* 80084234 */ .space 0x04

nonmatching D_80084238_ovl2, 0x4

dlabel D_80084238_ovl2
    /* 80084238 */ .space 0x04

nonmatching D_8008423C_ovl2, 0x4

dlabel D_8008423C_ovl2
    /* 8008423C */ .space 0x04

nonmatching D_80084240_ovl2, 0x20

dlabel D_80084240_ovl2
    /* 80084240 */ .space 0x20

nonmatching D_80084260_ovl2, 0x40

dlabel D_80084260_ovl2
    /* 80084260 */ .space 0x40

nonmatching D_800842A0_ovl2, 0x40

dlabel D_800842A0_ovl2
    /* 800842A0 */ .space 0x40

nonmatching D_800842E0_ovl2, 0x180

dlabel D_800842E0_ovl2
    /* 800842E0 */ .space 0x180

nonmatching D_80084460_ovl2, 0x4

dlabel D_80084460_ovl2
    /* 80084460 */ .space 0x04

nonmatching D_80084464_ovl2, 0x4

dlabel D_80084464_ovl2
    /* 80084464 */ .space 0x04

nonmatching D_80084468_ovl2, 0x4

dlabel D_80084468_ovl2
    /* 80084468 */ .space 0x04

nonmatching D_8008446C_ovl2, 0x4

dlabel D_8008446C_ovl2
    /* 8008446C */ .space 0x04

nonmatching D_80084470_ovl2, 0x10

dlabel D_80084470_ovl2
    /* 80084470 */ .space 0x10

nonmatching D_80084480_ovl2, 0x8

dlabel D_80084480_ovl2
    /* 80084480 */ .space 0x08

nonmatching D_80084488_ovl2, 0x4

dlabel D_80084488_ovl2
    /* 80084488 */ .space 0x04

nonmatching D_8008448C_ovl2, 0x4

dlabel D_8008448C_ovl2
    /* 8008448C */ .space 0x04

nonmatching D_80084490_ovl2, 0x10

dlabel D_80084490_ovl2
    /* 80084490 */ .space 0x10

nonmatching D_800844A0_ovl2, 0x4

dlabel D_800844A0_ovl2
    /* 800844A0 */ .space 0x04

nonmatching D_800844A4_ovl2, 0x8

dlabel D_800844A4_ovl2
    /* 800844A4 */ .space 0x08

nonmatching D_800844AC_ovl2, 0x4

dlabel D_800844AC_ovl2
    /* 800844AC */ .space 0x04

nonmatching D_800844B0_ovl2, 0x10

dlabel D_800844B0_ovl2
    /* 800844B0 */ .space 0x10

nonmatching D_800844C0_ovl2, 0x4

dlabel D_800844C0_ovl2
    /* 800844C0 */ .space 0x04

nonmatching D_800844C4_ovl2, 0x1C

dlabel D_800844C4_ovl2
    /* 800844C4 */ .space 0x1C

nonmatching D_800844E0_ovl2, 0x4

dlabel D_800844E0_ovl2
    /* 800844E0 */ .space 0x04

nonmatching D_800844E4_ovl2, 0x4

dlabel D_800844E4_ovl2
    /* 800844E4 */ .space 0x04

nonmatching D_800844E8_ovl2, 0x4

dlabel D_800844E8_ovl2
    /* 800844E8 */ .space 0x04

nonmatching D_800844EC_ovl2, 0x4

dlabel D_800844EC_ovl2
    /* 800844EC */ .space 0x04

nonmatching D_800844F0_ovl2, 0x10

dlabel D_800844F0_ovl2
    /* 800844F0 */ .space 0x10

nonmatching D_80084500_ovl2, 0x1

dlabel D_80084500_ovl2
    /* 80084500 */ .space 0x01

nonmatching D_80084501_ovl2, 0x1

dlabel D_80084501_ovl2
    /* 80084501 */ .space 0x01

nonmatching D_80084502_ovl2, 0x2

dlabel D_80084502_ovl2
    /* 80084502 */ .space 0x02

nonmatching D_80084504_ovl2, 0x4

dlabel D_80084504_ovl2
    /* 80084504 */ .space 0x04

nonmatching D_80084508_ovl2, 0x4

dlabel D_80084508_ovl2
    /* 80084508 */ .space 0x04

nonmatching D_8008450C_ovl2, 0x4

dlabel D_8008450C_ovl2
    /* 8008450C */ .space 0x04

nonmatching D_80084510_ovl2, 0x4

dlabel D_80084510_ovl2
    /* 80084510 */ .space 0x04

nonmatching D_80084514_ovl2, 0x4

dlabel D_80084514_ovl2
    /* 80084514 */ .space 0x04

nonmatching D_80084518_ovl2, 0x4

dlabel D_80084518_ovl2
    /* 80084518 */ .space 0x04

nonmatching D_8008451C_ovl2, 0x44

dlabel D_8008451C_ovl2
    /* 8008451C */ .space 0x44

nonmatching D_80084560_ovl2, 0x1

dlabel D_80084560_ovl2
    /* 80084560 */ .space 0x01

nonmatching D_80084561_ovl2, 0x1

dlabel D_80084561_ovl2
    /* 80084561 */ .space 0x01

nonmatching D_80084562_ovl2, 0x2

dlabel D_80084562_ovl2
    /* 80084562 */ .space 0x02

nonmatching D_80084564_ovl2, 0x4

dlabel D_80084564_ovl2
    /* 80084564 */ .space 0x04

nonmatching D_80084568_ovl2, 0x14

dlabel D_80084568_ovl2
    /* 80084568 */ .space 0x14

nonmatching D_8008457C_ovl2, 0x2

dlabel D_8008457C_ovl2
    /* 8008457C */ .space 0x02

nonmatching D_8008457E_ovl2, 0x2

dlabel D_8008457E_ovl2
    /* 8008457E */ .space 0x02

nonmatching D_80084580_ovl2, 0x4

dlabel D_80084580_ovl2
    /* 80084580 */ .space 0x04

nonmatching D_80084584_ovl2, 0x4

dlabel D_80084584_ovl2
    /* 80084584 */ .space 0x04

nonmatching D_80084588_ovl2, 0x4

dlabel D_80084588_ovl2
    /* 80084588 */ .space 0x04

nonmatching D_8008458C_ovl2, 0x4

dlabel D_8008458C_ovl2
    /* 8008458C */ .space 0x04

nonmatching D_80084590_ovl2, 0x4

dlabel D_80084590_ovl2
    /* 80084590 */ .space 0x04

nonmatching D_80084594_ovl2, 0x4

dlabel D_80084594_ovl2
    /* 80084594 */ .space 0x04

nonmatching D_80084598_ovl2, 0x4

dlabel D_80084598_ovl2
    /* 80084598 */ .space 0x04

nonmatching D_8008459C_ovl2, 0x4

dlabel D_8008459C_ovl2
    /* 8008459C */ .space 0x04

nonmatching D_800845A0_ovl2, 0x4

dlabel D_800845A0_ovl2
    /* 800845A0 */ .space 0x04

nonmatching D_800845A4_ovl2, 0x4

dlabel D_800845A4_ovl2
    /* 800845A4 */ .space 0x04

nonmatching D_800845A8_ovl2, 0x4

dlabel D_800845A8_ovl2
    /* 800845A8 */ .space 0x04

nonmatching D_800845AC_ovl2, 0x4

dlabel D_800845AC_ovl2
    /* 800845AC */ .space 0x04

nonmatching D_800845B0_ovl2, 0x4

dlabel D_800845B0_ovl2
    /* 800845B0 */ .space 0x04

nonmatching D_800845B4_ovl2, 0x4

dlabel D_800845B4_ovl2
    /* 800845B4 */ .space 0x04

nonmatching D_800845B8_ovl2, 0x4

dlabel D_800845B8_ovl2
    /* 800845B8 */ .space 0x04

nonmatching D_800845BC_ovl2, 0x2

dlabel D_800845BC_ovl2
    /* 800845BC */ .space 0x02

nonmatching D_800845BE_ovl2, 0x2

dlabel D_800845BE_ovl2
    /* 800845BE */ .space 0x02

nonmatching D_800845C0_ovl2, 0x4

dlabel D_800845C0_ovl2
    /* 800845C0 */ .space 0x04

nonmatching D_800845C4_ovl2, 0x4

dlabel D_800845C4_ovl2
    /* 800845C4 */ .space 0x04

nonmatching D_800845C8_ovl2, 0x4

dlabel D_800845C8_ovl2
    /* 800845C8 */ .space 0x04

nonmatching D_800845CC_ovl2, 0x4

dlabel D_800845CC_ovl2
    /* 800845CC */ .space 0x04

nonmatching D_800845D0_ovl2, 0x4

dlabel D_800845D0_ovl2
    /* 800845D0 */ .space 0x04

nonmatching D_800845D4_ovl2, 0x4

dlabel D_800845D4_ovl2
    /* 800845D4 */ .space 0x04

nonmatching D_800845D8_ovl2, 0x4

dlabel D_800845D8_ovl2
    /* 800845D8 */ .space 0x04

nonmatching D_800845DC_ovl2, 0x4

dlabel D_800845DC_ovl2
    /* 800845DC */ .space 0x04

nonmatching D_800845E0_ovl2, 0x4

dlabel D_800845E0_ovl2
    /* 800845E0 */ .space 0x04

nonmatching D_800845E4_ovl2, 0x4

dlabel D_800845E4_ovl2
    /* 800845E4 */ .space 0x04

nonmatching D_800845E8_ovl2, 0x4

dlabel D_800845E8_ovl2
    /* 800845E8 */ .space 0x04

nonmatching D_800845EC_ovl2, 0x4

dlabel D_800845EC_ovl2
    /* 800845EC */ .space 0x04

nonmatching D_800845F0_ovl2, 0x2

dlabel D_800845F0_ovl2
    /* 800845F0 */ .space 0x02

nonmatching D_800845F2_ovl2, 0x2

dlabel D_800845F2_ovl2
    /* 800845F2 */ .space 0x02

nonmatching D_800845F4_ovl2, 0x4

dlabel D_800845F4_ovl2
    /* 800845F4 */ .space 0x04

nonmatching D_800845F8_ovl2, 0x4

dlabel D_800845F8_ovl2
    /* 800845F8 */ .space 0x04

nonmatching D_800845FC_ovl2, 0x4

dlabel D_800845FC_ovl2
    /* 800845FC */ .space 0x04

nonmatching D_80084600_ovl2, 0x4

dlabel D_80084600_ovl2
    /* 80084600 */ .space 0x04

nonmatching D_80084604_ovl2, 0x4

dlabel D_80084604_ovl2
    /* 80084604 */ .space 0x04

nonmatching D_80084608_ovl2, 0x4

dlabel D_80084608_ovl2
    /* 80084608 */ .space 0x04

nonmatching D_8008460C_ovl2, 0x4

dlabel D_8008460C_ovl2
    /* 8008460C */ .space 0x04

nonmatching D_80084610_ovl2, 0x4

dlabel D_80084610_ovl2
    /* 80084610 */ .space 0x04

nonmatching D_80084614_ovl2, 0x8

dlabel D_80084614_ovl2
    /* 80084614 */ .space 0x08

nonmatching D_8008461C_ovl2, 0x4

dlabel D_8008461C_ovl2
    /* 8008461C */ .space 0x04

nonmatching D_80084620_ovl2, 0x4

dlabel D_80084620_ovl2
    /* 80084620 */ .space 0x04

nonmatching D_80084624_ovl2, 0x4

dlabel D_80084624_ovl2
    /* 80084624 */ .space 0x04

nonmatching D_80084628_ovl2, 0x4

dlabel D_80084628_ovl2
    /* 80084628 */ .space 0x04

nonmatching D_8008462C_ovl2, 0x4

dlabel D_8008462C_ovl2
    /* 8008462C */ .space 0x04

nonmatching D_80084630_ovl2, 0x790

dlabel D_80084630_ovl2
    /* 80084630 */ .space 0x790

nonmatching D_80084DC0_ovl2, 0x4

dlabel D_80084DC0_ovl2
    /* 80084DC0 */ .space 0x04

nonmatching D_80084DC4_ovl2, 0xC

dlabel D_80084DC4_ovl2
    /* 80084DC4 */ .space 0x0C
