.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.39.3 */

.align 3
nonmatching D_803A8BC0_ovl8

dlabel D_803A8BC0_ovl8
    /* 1BAC40 803A8BC0 3FF8000000000000 */ .double 1.5
    /* 1BAC48 803A8BC8 0000000000000000 */ .double 0
enddlabel D_803A8BC0_ovl8

.align 3
nonmatching D_803A8BD0_ovl8

dlabel D_803A8BD0_ovl8
    /* 1BAC50 803A8BD0 408F3F3340000000 */ .double 999.9000244140625
enddlabel D_803A8BD0_ovl8

.align 3
nonmatching D_803A8BD8_ovl8

dlabel D_803A8BD8_ovl8
    /* 1BAC58 803A8BD8 40030C30C30C30C3 */ .double 2.38095238095238093
enddlabel D_803A8BD8_ovl8

.align 3
nonmatching D_803A8BE0_ovl8

dlabel D_803A8BE0_ovl8
    /* 1BAC60 803A8BE0 40030C30C30C30C3 */ .double 2.38095238095238093
enddlabel D_803A8BE0_ovl8

.align 3
nonmatching D_803A8BE8_ovl8

dlabel D_803A8BE8_ovl8
    /* 1BAC68 803A8BE8 4024000000000000 */ .double 10
enddlabel D_803A8BE8_ovl8

.align 3
nonmatching D_803A8BF0_ovl8

dlabel D_803A8BF0_ovl8
    /* 1BAC70 803A8BF0 3FF30C30C30C30C3 */ .double 1.19047619047619047
enddlabel D_803A8BF0_ovl8

.align 3
nonmatching D_803A8BF8_ovl8

dlabel D_803A8BF8_ovl8
    /* 1BAC78 803A8BF8 40030C30C30C30C3 */ .double 2.38095238095238093
enddlabel D_803A8BF8_ovl8

.align 3
nonmatching D_803A8C00_ovl8

dlabel D_803A8C00_ovl8
    /* 1BAC80 803A8C00 4059000000000000 */ .double 100
enddlabel D_803A8C00_ovl8

.align 3
nonmatching D_803A8C08_ovl8

dlabel D_803A8C08_ovl8
    /* 1BAC88 803A8C08 403C48C60029F16B */ .double 28.2842712499999998
enddlabel D_803A8C08_ovl8

.align 3
nonmatching D_803A8C10_ovl8

dlabel D_803A8C10_ovl8
    /* 1BAC90 803A8C10 4059000000000000 */ .double 100
enddlabel D_803A8C10_ovl8

.align 3
nonmatching D_803A8C18_ovl8

dlabel D_803A8C18_ovl8
    /* 1BAC98 803A8C18 4024000000000000 */ .double 10
enddlabel D_803A8C18_ovl8

nonmatching D_803A8C20_ovl8

dlabel D_803A8C20_ovl8
    /* 1BACA0 803A8C20 40590000 */ .word 0x40590000
enddlabel D_803A8C20_ovl8

nonmatching D_803A8C24_ovl8

dlabel D_803A8C24_ovl8
    /* 1BACA4 803A8C24 00000000 */ .word 0x00000000
enddlabel D_803A8C24_ovl8

nonmatching D_803A8C28_ovl8

dlabel D_803A8C28_ovl8
    /* 1BACA8 803A8C28 C0490000 */ .word 0xC0490000
enddlabel D_803A8C28_ovl8

nonmatching D_803A8C2C_ovl8

dlabel D_803A8C2C_ovl8
    /* 1BACAC 803A8C2C 00000000 */ .word 0x00000000
enddlabel D_803A8C2C_ovl8

.align 3
nonmatching D_803A8C30_ovl8

dlabel D_803A8C30_ovl8
    /* 1BACB0 803A8C30 4059000000000000 */ .double 100
enddlabel D_803A8C30_ovl8

.align 3
nonmatching D_803A8C38_ovl8

dlabel D_803A8C38_ovl8
    /* 1BACB8 803A8C38 4059000000000000 */ .double 100
enddlabel D_803A8C38_ovl8

.align 2
nonmatching D_803A8C40_ovl8

dlabel D_803A8C40_ovl8
    /* 1BACC0 803A8C40 */ .asciz "pt00"
    /* 7074303000000000 */
.align 2
.align 2
    /* 1BACC8 803A8C48 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 1BACCC 803A8C4C */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_803A8C40_ovl8

.align 3
nonmatching D_803A8C50_ovl8

dlabel D_803A8C50_ovl8
    /* 1BACD0 803A8C50 3F91DF46A2529D39 */ .double 0.0174532925199432955
    /* 1BACD8 803A8C58 0000000000000000 */ .double 0
enddlabel D_803A8C50_ovl8

.align 2
nonmatching D_803A8C60_ovl8

dlabel D_803A8C60_ovl8
    /* 1BACE0 803A8C60 */ .asciz "SAV"
    /* 53415600 */
.align 2
enddlabel D_803A8C60_ovl8

.align 2
nonmatching D_803A8C64_ovl8

dlabel D_803A8C64_ovl8
    /* 1BACE4 803A8C64 */ .asciz "EDT"
    /* 45445400 */
.align 2
enddlabel D_803A8C64_ovl8

.align 2
nonmatching D_803A8C68_ovl8

dlabel D_803A8C68_ovl8
    /* 1BACE8 803A8C68 */ .asciz "CHR"
    /* 43485200 */
.align 2
enddlabel D_803A8C68_ovl8

nonmatching D_803A8C6C_ovl8

dlabel D_803A8C6C_ovl8
    /* 1BACEC 803A8C6C 00000000 */ .word 0x00000000
enddlabel D_803A8C6C_ovl8

.align 2
nonmatching D_803A8C70_ovl8

dlabel D_803A8C70_ovl8
    /* 1BACF0 803A8C70 */ .asciz "NO :"
    /* 4E4F203A00000000 */
.align 2
enddlabel D_803A8C70_ovl8

.align 2
nonmatching D_803A8C78_ovl8

dlabel D_803A8C78_ovl8
    /* 1BACF8 803A8C78 */ .asciz "HIT"
    /* 48495400 */
.align 2
enddlabel D_803A8C78_ovl8

.align 2
nonmatching D_803A8C7C_ovl8

dlabel D_803A8C7C_ovl8
    /* 1BACFC 803A8C7C */ .asciz "MOV"
    /* 4D4F5600 */
.align 2
enddlabel D_803A8C7C_ovl8

.align 2
nonmatching D_803A8C80_ovl8

dlabel D_803A8C80_ovl8
    /* 1BAD00 803A8C80 */ .asciz "WEP:"
    /* 5745503A00000000 */
.align 2
enddlabel D_803A8C80_ovl8

.align 2
nonmatching D_803A8C88_ovl8

dlabel D_803A8C88_ovl8
    /* 1BAD08 803A8C88 */ .asciz "STP:"
    /* 5354503A00000000 */
.align 2
enddlabel D_803A8C88_ovl8

.align 2
nonmatching D_803A8C90_ovl8

dlabel D_803A8C90_ovl8
    /* 1BAD10 803A8C90 */ .asciz "DAT:"
    /* 4441543A00000000 */
.align 2
enddlabel D_803A8C90_ovl8

.align 2
nonmatching D_803A8C98_ovl8

dlabel D_803A8C98_ovl8
    /* 1BAD18 803A8C98 */ .asciz "MOD:"
    /* 4D4F443A00000000 */
.align 2
enddlabel D_803A8C98_ovl8

.align 2
nonmatching D_803A8CA0_ovl8

dlabel D_803A8CA0_ovl8
    /* 1BAD20 803A8CA0 */ .asciz "grid"
    /* 6772696400000000 */
.align 2
enddlabel D_803A8CA0_ovl8

nonmatching D_803A8CA8_ovl8

dlabel D_803A8CA8_ovl8
    /* 1BAD28 803A8CA8 72776561 */ .word 0x72776561
    /* 1BAD2C 803A8CAC 70000000 */ .word 0x70000000
enddlabel D_803A8CA8_ovl8

nonmatching D_803A8CB0_ovl8

dlabel D_803A8CB0_ovl8
    /* 1BAD30 803A8CB0 726F6F74 */ .word 0x726F6F74
    /* 1BAD34 803A8CB4 00000000 */ .word 0x00000000
enddlabel D_803A8CB0_ovl8

nonmatching D_803A8CB8_ovl8

dlabel D_803A8CB8_ovl8
    /* 1BAD38 803A8CB8 626C6164 */ .word 0x626C6164
    /* 1BAD3C 803A8CBC 65000000 */ .word 0x65000000
enddlabel D_803A8CB8_ovl8

.align 2
nonmatching D_803A8CC0_ovl8

dlabel D_803A8CC0_ovl8
    /* 1BAD40 803A8CC0 */ .asciz "lshou"
    /* 6C73686F75000000 */
.align 2
enddlabel D_803A8CC0_ovl8

.align 2
nonmatching D_803A8CC8_ovl8

dlabel D_803A8CC8_ovl8
    /* 1BAD48 803A8CC8 */ .asciz "rshou"
    /* 7273686F75000000 */
.align 2
enddlabel D_803A8CC8_ovl8

.align 2
nonmatching D_803A8CD0_ovl8

dlabel D_803A8CD0_ovl8
    /* 1BAD50 803A8CD0 */ .asciz "face1"
    /* 6661636531000000 */
.align 2
enddlabel D_803A8CD0_ovl8

.align 2
nonmatching D_803A8CD8_ovl8

dlabel D_803A8CD8_ovl8
    /* 1BAD58 803A8CD8 */ .asciz "lblade"
    /* 6C626C6164650000 */
.align 2
enddlabel D_803A8CD8_ovl8

.align 2
nonmatching D_803A8CE0_ovl8

dlabel D_803A8CE0_ovl8
    /* 1BAD60 803A8CE0 */ .asciz "cable"
    /* 6361626C65000000 */
.align 2
enddlabel D_803A8CE0_ovl8

.align 2
nonmatching D_803A8CE8_ovl8

dlabel D_803A8CE8_ovl8
    /* 1BAD68 803A8CE8 */ .asciz "wing"
    /* 77696E6700000000 */
.align 2
enddlabel D_803A8CE8_ovl8

.align 2
nonmatching D_803A8CF0_ovl8

dlabel D_803A8CF0_ovl8
    /* 1BAD70 803A8CF0 */ .asciz "lhand"
    /* 6C68616E64000000 */
.align 2
enddlabel D_803A8CF0_ovl8

.align 2
nonmatching D_803A8CF8_ovl8

dlabel D_803A8CF8_ovl8
    /* 1BAD78 803A8CF8 */ .asciz "muti"
    /* 6D75746900000000 */
.align 2
enddlabel D_803A8CF8_ovl8

.align 2
nonmatching D_803A8D00_ovl8

dlabel D_803A8D00_ovl8
    /* 1BAD80 803A8D00 */ .asciz "rhand"
    /* 7268616E64000000 */
.align 2
enddlabel D_803A8D00_ovl8

.align 2
nonmatching D_803A8D08_ovl8

dlabel D_803A8D08_ovl8
    /* 1BAD88 803A8D08 */ .asciz "lweap"
    /* 6C77656170000000 */
.align 2
enddlabel D_803A8D08_ovl8

.align 2
nonmatching D_803A8D10_ovl8

dlabel D_803A8D10_ovl8
    /* 1BAD90 803A8D10 */ .asciz "lyari"
    /* 6C79617269000000 */
.align 2
enddlabel D_803A8D10_ovl8

.align 2
nonmatching D_803A8D18_ovl8

dlabel D_803A8D18_ovl8
    /* 1BAD98 803A8D18 */ .asciz "-CHAR DATA EDIT-"
    /* 2D43484152204441544120454449542D00000000 */
.align 2
enddlabel D_803A8D18_ovl8

.align 2
nonmatching D_803A8D2C_ovl8

dlabel D_803A8D2C_ovl8
    /* 1BADAC 803A8D2C */ .asciz "KEY:%d.%d(%d)  "
    /* 4B45593A25642E256428256429202000 */
.align 2
enddlabel D_803A8D2C_ovl8

.align 2
nonmatching D_803A8D3C_ovl8

dlabel D_803A8D3C_ovl8
    /* 1BADBC 803A8D3C */ .asciz "CNT:%d "
    /* 434E543A25642000 */
.align 2
enddlabel D_803A8D3C_ovl8

.align 2
nonmatching D_803A8D44_ovl8

dlabel D_803A8D44_ovl8
    /* 1BADC4 803A8D44 */ .asciz "%-15s"
    /* 252D313573000000 */
.align 2
enddlabel D_803A8D44_ovl8

.align 2
nonmatching D_803A8D4C_ovl8

dlabel D_803A8D4C_ovl8
    /* 1BADCC 803A8D4C */ .asciz "--:-----          "
    /* 2D2D3A2D2D2D2D2D202020202020202020200000 */
.align 2
enddlabel D_803A8D4C_ovl8

.align 2
nonmatching D_803A8D60_ovl8

dlabel D_803A8D60_ovl8
    /* 1BADE0 803A8D60 */ .asciz "%2d:%5.2f          "
    /* 2532643A25352E32662020202020202020202000 */
.align 2
enddlabel D_803A8D60_ovl8

nonmatching D_803A8D74_ovl8

dlabel D_803A8D74_ovl8
    /* 1BADF4 803A8D74 20202020 */ .word 0x20202020
    /* 1BADF8 803A8D78 20202020 */ .word 0x20202020
    /* 1BADFC 803A8D7C 20202020 */ .word 0x20202020
    /* 1BAE00 803A8D80 20202020 */ .word 0x20202020
    /* 1BAE04 803A8D84 20200000 */ .word 0x20200000
enddlabel D_803A8D74_ovl8

nonmatching D_803A8D88_ovl8

dlabel D_803A8D88_ovl8
    /* 1BAE08 803A8D88 80000000 */ .float -0
enddlabel D_803A8D88_ovl8

.align 2
nonmatching D_803A8D8C_ovl8

dlabel D_803A8D8C_ovl8
    /* 1BAE0C 803A8D8C */ .asciz "--:---------------"
    /* 2D2D3A2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D0000 */
.align 2
enddlabel D_803A8D8C_ovl8

.align 2
nonmatching D_803A8DA0_ovl8

dlabel D_803A8DA0_ovl8
    /* 1BAE20 803A8DA0 */ .asciz "%2d:%3d,%3d,%3d,%3d"
    /* 2532643A2533642C2533642C2533642C25336400 */
.align 2
enddlabel D_803A8DA0_ovl8

.align 2
nonmatching D_803A8DB4_ovl8

dlabel D_803A8DB4_ovl8
    /* 1BAE34 803A8DB4 */ .asciz "ATTACK_ATF_CHOP"
    /* 41545441434B5F4154465F43484F5000 */
.align 2
enddlabel D_803A8DB4_ovl8

.align 2
nonmatching D_803A8DC4_ovl8

dlabel D_803A8DC4_ovl8
    /* 1BAE44 803A8DC4 */ .asciz "ATF_PRESS_1"
    /* 4154465F50524553535F3100 */
.align 2
enddlabel D_803A8DC4_ovl8

.align 2
nonmatching D_803A8DD0_ovl8

dlabel D_803A8DD0_ovl8
    /* 1BAE50 803A8DD0 */ .asciz "ATTACK_RONGI"
    /* 41545441434B5F524F4E474900000000 */
.align 2
enddlabel D_803A8DD0_ovl8

.align 2
nonmatching D_803A8DE0_ovl8

dlabel D_803A8DE0_ovl8
    /* 1BAE60 803A8DE0 */ .asciz "ATTACK_SWORD"
    /* 41545441434B5F53574F524400000000 */
.align 2
enddlabel D_803A8DE0_ovl8

.align 2
nonmatching D_803A8DF0_ovl8

dlabel D_803A8DF0_ovl8
    /* 1BAE70 803A8DF0 */ .asciz "ATTACK_SPINKICK"
    /* 41545441434B5F5350494E4B49434B00 */
.align 2
enddlabel D_803A8DF0_ovl8

.align 2
nonmatching D_803A8E00_ovl8

dlabel D_803A8E00_ovl8
    /* 1BAE80 803A8E00 */ .asciz "ATTACK_HEEL"
    /* 41545441434B5F4845454C00 */
.align 2
enddlabel D_803A8E00_ovl8

.align 2
nonmatching D_803A8E0C_ovl8

dlabel D_803A8E0C_ovl8
    /* 1BAE8C 803A8E0C */ .asciz "ATTACK_CHOP"
    /* 41545441434B5F43484F5000 */
.align 2
enddlabel D_803A8E0C_ovl8

.align 2
nonmatching D_803A8E18_ovl8

dlabel D_803A8E18_ovl8
    /* 1BAE98 803A8E18 */ .asciz "ATTACK_KNOCK"
    /* 41545441434B5F4B4E4F434B00000000 */
.align 2
enddlabel D_803A8E18_ovl8

.align 2
nonmatching D_803A8E28_ovl8

dlabel D_803A8E28_ovl8
    /* 1BAEA8 803A8E28 */ .asciz "ATTACK_PKNIFE3"
    /* 41545441434B5F504B4E494645330000 */
.align 2
enddlabel D_803A8E28_ovl8

.align 2
nonmatching D_803A8E38_ovl8

dlabel D_803A8E38_ovl8
    /* 1BAEB8 803A8E38 */ .asciz "ATTACK_PKNIFE2"
    /* 41545441434B5F504B4E494645320000 */
.align 2
enddlabel D_803A8E38_ovl8

.align 2
nonmatching D_803A8E48_ovl8

dlabel D_803A8E48_ovl8
    /* 1BAEC8 803A8E48 */ .asciz "ATTACK_PKNIFE1"
    /* 41545441434B5F504B4E494645310000 */
.align 2
enddlabel D_803A8E48_ovl8

.align 2
nonmatching D_803A8E58_ovl8

dlabel D_803A8E58_ovl8
    /* 1BAED8 803A8E58 */ .asciz "ATTACK_BIG_C"
    /* 41545441434B5F4249475F4300000000 */
.align 2
enddlabel D_803A8E58_ovl8

.align 2
nonmatching D_803A8E68_ovl8

dlabel D_803A8E68_ovl8
    /* 1BAEE8 803A8E68 */ .asciz "ATTACK_BIG_K"
    /* 41545441434B5F4249475F4B00000000 */
.align 2
enddlabel D_803A8E68_ovl8

.align 2
nonmatching D_803A8E78_ovl8

dlabel D_803A8E78_ovl8
    /* 1BAEF8 803A8E78 */ .asciz "ATTACK_BIG_P"
    /* 41545441434B5F4249475F5000000000 */
.align 2
enddlabel D_803A8E78_ovl8

.align 2
nonmatching D_803A8E88_ovl8

dlabel D_803A8E88_ovl8
    /* 1BAF08 803A8E88 */ .asciz "ATTACK_CATCH"
    /* 41545441434B5F434154434800000000 */
.align 2
enddlabel D_803A8E88_ovl8

.align 2
nonmatching D_803A8E98_ovl8

dlabel D_803A8E98_ovl8
    /* 1BAF18 803A8E98 */ .asciz "ATTACK_KICK"
    /* 41545441434B5F4B49434B00 */
.align 2
enddlabel D_803A8E98_ovl8

.align 2
nonmatching D_803A8EA4_ovl8

dlabel D_803A8EA4_ovl8
    /* 1BAF24 803A8EA4 */ .asciz "ATTACK_PUNCH2"
    /* 41545441434B5F50554E434832000000 */
.align 2
enddlabel D_803A8EA4_ovl8

.align 2
nonmatching D_803A8EB4_ovl8

dlabel D_803A8EB4_ovl8
    /* 1BAF34 803A8EB4 */ .asciz "ATTACK_PUNCH1"
    /* 41545441434B5F50554E434831000000 */
.align 2
enddlabel D_803A8EB4_ovl8

.align 2
nonmatching D_803A8EC4_ovl8

dlabel D_803A8EC4_ovl8
    /* 1BAF44 803A8EC4 */ .asciz "WAKEUP"
    /* 57414B4555500000 */
.align 2
enddlabel D_803A8EC4_ovl8

.align 2
nonmatching D_803A8ECC_ovl8

dlabel D_803A8ECC_ovl8
    /* 1BAF4C 803A8ECC */ .asciz "DAMAGE_UPPER"
    /* 44414D4147455F555050455200000000 */
.align 2
enddlabel D_803A8ECC_ovl8

.align 2
nonmatching D_803A8EDC_ovl8

dlabel D_803A8EDC_ovl8
    /* 1BAF5C 803A8EDC */ .asciz "M13_DAMAGE_MIDDLE_1"
    /* 4D31335F44414D4147455F4D4944444C455F3100 */
.align 2
enddlabel D_803A8EDC_ovl8

.align 2
nonmatching D_803A8EF0_ovl8

dlabel D_803A8EF0_ovl8
    /* 1BAF70 803A8EF0 */ .asciz "DAMAGE_MIDDLE_0"
    /* 44414D4147455F4D4944444C455F3000 */
.align 2
enddlabel D_803A8EF0_ovl8

.align 2
nonmatching D_803A8F00_ovl8

dlabel D_803A8F00_ovl8
    /* 1BAF80 803A8F00 */ .asciz "DAMAGE_SMALL_1"
    /* 44414D4147455F534D414C4C5F310000 */
.align 2
enddlabel D_803A8F00_ovl8

.align 2
nonmatching D_803A8F10_ovl8

dlabel D_803A8F10_ovl8
    /* 1BAF90 803A8F10 */ .asciz "DAMAGE_SMALL_0"
    /* 44414D4147455F534D414C4C5F300000 */
.align 2
enddlabel D_803A8F10_ovl8

.align 2
nonmatching D_803A8F20_ovl8

dlabel D_803A8F20_ovl8
    /* 1BAFA0 803A8F20 */ .asciz "ATF_PRESS"
    /* 4154465F5052455353000000 */
.align 2
enddlabel D_803A8F20_ovl8

.align 2
nonmatching D_803A8F2C_ovl8

dlabel D_803A8F2C_ovl8
    /* 1BAFAC 803A8F2C */ .asciz "ATF_OPEN_1"
    /* 4154465F4F50454E5F310000 */
.align 2
enddlabel D_803A8F2C_ovl8

.align 2
nonmatching D_803A8F38_ovl8

dlabel D_803A8F38_ovl8
    /* 1BAFB8 803A8F38 */ .asciz "ATF_OPEN_0"
    /* 4154465F4F50454E5F300000 */
.align 2
enddlabel D_803A8F38_ovl8

.align 2
nonmatching D_803A8F44_ovl8

dlabel D_803A8F44_ovl8
    /* 1BAFC4 803A8F44 */ .asciz "AVOID_JUMP_1"
    /* 41564F49445F4A554D505F3100000000 */
.align 2
enddlabel D_803A8F44_ovl8

.align 2
nonmatching D_803A8F54_ovl8

dlabel D_803A8F54_ovl8
    /* 1BAFD4 803A8F54 */ .asciz "AVOID_JUMP_0"
    /* 41564F49445F4A554D505F3000000000 */
.align 2
enddlabel D_803A8F54_ovl8

.align 2
nonmatching D_803A8F64_ovl8

dlabel D_803A8F64_ovl8
    /* 1BAFE4 803A8F64 */ .asciz "AVOID_CROUCH"
    /* 41564F49445F43524F55434800000000 */
.align 2
enddlabel D_803A8F64_ovl8

.align 2
nonmatching D_803A8F74_ovl8

dlabel D_803A8F74_ovl8
    /* 1BAFF4 803A8F74 */ .asciz "AVOID_GUARD_1"
    /* 41564F49445F47554152445F31000000 */
.align 2
enddlabel D_803A8F74_ovl8

.align 2
nonmatching D_803A8F84_ovl8

dlabel D_803A8F84_ovl8
    /* 1BB004 803A8F84 */ .asciz "AVOID_GUARD_0"
    /* 41564F49445F47554152445F30000000 */
.align 2
enddlabel D_803A8F84_ovl8

.align 2
nonmatching D_803A8F94_ovl8

dlabel D_803A8F94_ovl8
    /* 1BB014 803A8F94 */ .asciz "MISS_TACKLE"
    /* 4D4953535F5441434B4C4500 */
.align 2
enddlabel D_803A8F94_ovl8

.align 2
nonmatching D_803A8FA0_ovl8

dlabel D_803A8FA0_ovl8
    /* 1BB020 803A8FA0 */ .asciz "STOP_DASH"
    /* 53544F505F44415348000000 */
.align 2
enddlabel D_803A8FA0_ovl8

.align 2
nonmatching D_803A8FAC_ovl8

dlabel D_803A8FAC_ovl8
    /* 1BB02C 803A8FAC */ .asciz "DASH"
    /* 4441534800000000 */
.align 2
enddlabel D_803A8FAC_ovl8

.align 2
nonmatching D_803A8FB4_ovl8

dlabel D_803A8FB4_ovl8
    /* 1BB034 803A8FB4 */ .asciz "SWAY_BACK"
    /* 535741595F4241434B000000 */
.align 2
enddlabel D_803A8FB4_ovl8

.align 2
nonmatching D_803A8FC0_ovl8

dlabel D_803A8FC0_ovl8
    /* 1BB040 803A8FC0 */ .asciz "SWAY_FRONT"
    /* 535741595F46524F4E540000 */
.align 2
enddlabel D_803A8FC0_ovl8

.align 2
nonmatching D_803A8FCC_ovl8

dlabel D_803A8FCC_ovl8
    /* 1BB04C 803A8FCC */ .asciz "STOP_LEFT_1"
    /* 53544F505F4C4546545F3100 */
.align 2
enddlabel D_803A8FCC_ovl8

.align 2
nonmatching D_803A8FD8_ovl8

dlabel D_803A8FD8_ovl8
    /* 1BB058 803A8FD8 */ .asciz "STOP_LEFT_0"
    /* 53544F505F4C4546545F3000 */
.align 2
enddlabel D_803A8FD8_ovl8

.align 2
nonmatching D_803A8FE4_ovl8

dlabel D_803A8FE4_ovl8
    /* 1BB064 803A8FE4 */ .asciz "STOP_RIGHT_1"
    /* 53544F505F52494748545F3100000000 */
.align 2
enddlabel D_803A8FE4_ovl8

.align 2
nonmatching D_803A8FF4_ovl8

dlabel D_803A8FF4_ovl8
    /* 1BB074 803A8FF4 */ .asciz "STOP_RIGHT_0"
    /* 53544F505F52494748545F3000000000 */
.align 2
enddlabel D_803A8FF4_ovl8

.align 2
nonmatching D_803A9004_ovl8

dlabel D_803A9004_ovl8
    /* 1BB084 803A9004 */ .asciz "TURN_1"
    /* 5455524E5F310000 */
.align 2
enddlabel D_803A9004_ovl8

.align 2
nonmatching D_803A900C_ovl8

dlabel D_803A900C_ovl8
    /* 1BB08C 803A900C */ .asciz "TURN_0"
    /* 5455524E5F300000 */
.align 2
enddlabel D_803A900C_ovl8

.align 2
nonmatching D_803A9014_ovl8

dlabel D_803A9014_ovl8
    /* 1BB094 803A9014 */ .asciz "WALK_BACK_2"
    /* 57414C4B5F4241434B5F3200 */
.align 2
enddlabel D_803A9014_ovl8

.align 2
nonmatching D_803A9020_ovl8

dlabel D_803A9020_ovl8
    /* 1BB0A0 803A9020 */ .asciz "WALK_BACK_1"
    /* 57414C4B5F4241434B5F3100 */
.align 2
enddlabel D_803A9020_ovl8

.align 2
nonmatching D_803A902C_ovl8

dlabel D_803A902C_ovl8
    /* 1BB0AC 803A902C */ .asciz "WALK_BACK_0"
    /* 57414C4B5F4241434B5F3000 */
.align 2
enddlabel D_803A902C_ovl8

.align 2
nonmatching D_803A9038_ovl8

dlabel D_803A9038_ovl8
    /* 1BB0B8 803A9038 */ .asciz "WALK_FRONT_1"
    /* 57414C4B5F46524F4E545F3100000000 */
.align 2
enddlabel D_803A9038_ovl8

.align 2
nonmatching D_803A9048_ovl8

dlabel D_803A9048_ovl8
    /* 1BB0C8 803A9048 */ .asciz "WALK_FRONT_0"
    /* 57414C4B5F46524F4E545F3000000000 */
.align 2
enddlabel D_803A9048_ovl8

.align 2
nonmatching D_803A9058_ovl8

dlabel D_803A9058_ovl8
    /* 1BB0D8 803A9058 */ .asciz "STAND_1"
    /* 5354414E445F3100 */
.align 2
enddlabel D_803A9058_ovl8

.align 2
nonmatching D_803A9060_ovl8

dlabel D_803A9060_ovl8
    /* 1BB0E0 803A9060 */ .asciz "STAND_0"
    /* 5354414E445F3000 */
.align 2
enddlabel D_803A9060_ovl8

.align 2
nonmatching D_803A9068_ovl8

dlabel D_803A9068_ovl8
    /* 1BB0E8 803A9068 */ .asciz "DAMAGE_LARGE"
    /* 44414D4147455F4C4152474500000000 */
.align 2
enddlabel D_803A9068_ovl8

.align 2
nonmatching D_803A9078_ovl8

dlabel D_803A9078_ovl8
    /* 1BB0F8 803A9078 */ .asciz "DAMAGE_SMALL"
    /* 44414D4147455F534D414C4C00000000 */
.align 2
enddlabel D_803A9078_ovl8

.align 2
nonmatching D_803A9088_ovl8

dlabel D_803A9088_ovl8
    /* 1BB108 803A9088 */ .asciz "MOVE_BACK"
    /* 4D4F56455F4241434B000000 */
.align 2
enddlabel D_803A9088_ovl8

.align 2
nonmatching D_803A9094_ovl8

dlabel D_803A9094_ovl8
    /* 1BB114 803A9094 */ .asciz "MOVE_FRONT"
    /* 4D4F56455F46524F4E540000 */
.align 2
enddlabel D_803A9094_ovl8

.align 2
nonmatching D_803A90A0_ovl8

dlabel D_803A90A0_ovl8
    /* 1BB120 803A90A0 */ .asciz "STAND"
    /* 5354414E44000000 */
.align 2
enddlabel D_803A90A0_ovl8

.align 2
nonmatching D_803A90A8_ovl8

dlabel D_803A90A8_ovl8
    /* 1BB128 803A90A8 */ .asciz "ATTACK_PILE_L"
    /* 41545441434B5F50494C455F4C000000 */
.align 2
enddlabel D_803A90A8_ovl8

.align 2
nonmatching D_803A90B8_ovl8

dlabel D_803A90B8_ovl8
    /* 1BB138 803A90B8 */ .asciz "ATTACK_PILE_R"
    /* 41545441434B5F50494C455F52000000 */
.align 2
enddlabel D_803A90B8_ovl8

.align 2
nonmatching D_803A90C8_ovl8

dlabel D_803A90C8_ovl8
    /* 1BB148 803A90C8 */ .asciz "DAMAGE_KICK"
    /* 44414D4147455F4B49434B00 */
.align 2
enddlabel D_803A90C8_ovl8

.align 2
nonmatching D_803A90D4_ovl8

dlabel D_803A90D4_ovl8
    /* 1BB154 803A90D4 */ .asciz "DAMAGE_PUNCH2"
    /* 44414D4147455F50554E434832000000 */
.align 2
enddlabel D_803A90D4_ovl8

.align 2
nonmatching D_803A90E4_ovl8

dlabel D_803A90E4_ovl8
    /* 1BB164 803A90E4 */ .asciz "DAMAGE_PUNCH1"
    /* 44414D4147455F50554E434831000000 */
.align 2
enddlabel D_803A90E4_ovl8

.align 2
nonmatching D_803A90F4_ovl8

dlabel D_803A90F4_ovl8
    /* 1BB174 803A90F4 */ .asciz "DAMAGE_MIDDLE"
    /* 44414D4147455F4D4944444C45000000 */
.align 2
enddlabel D_803A90F4_ovl8

.align 2
nonmatching D_803A9104_ovl8

dlabel D_803A9104_ovl8
    /* 1BB184 803A9104 */ .asciz "STOP_LEFT"
    /* 53544F505F4C454654000000 */
.align 2
enddlabel D_803A9104_ovl8

.align 2
nonmatching D_803A9110_ovl8

dlabel D_803A9110_ovl8
    /* 1BB190 803A9110 */ .asciz "STOP_RIGHT"
    /* 53544F505F52494748540000 */
.align 2
enddlabel D_803A9110_ovl8

.align 2
nonmatching D_803A911C_ovl8

dlabel D_803A911C_ovl8
    /* 1BB19C 803A911C */ .asciz "WALK_BACK"
    /* 57414C4B5F4241434B000000 */
.align 2
enddlabel D_803A911C_ovl8

.align 2
nonmatching D_803A9128_ovl8

dlabel D_803A9128_ovl8
    /* 1BB1A8 803A9128 */ .asciz "WALK_FRONT"
    /* 57414C4B5F46524F4E540000 */
.align 2
enddlabel D_803A9128_ovl8

.align 2
nonmatching D_803A9134_ovl8

dlabel D_803A9134_ovl8
    /* 1BB1B4 803A9134 */ .asciz "ATTACK_THROW"
    /* 41545441434B5F5448524F5700000000 */
.align 2
enddlabel D_803A9134_ovl8

.align 2
nonmatching D_803A9144_ovl8

dlabel D_803A9144_ovl8
    /* 1BB1C4 803A9144 */ .asciz "ATTACK_LIFT"
    /* 41545441434B5F4C49465400 */
.align 2
enddlabel D_803A9144_ovl8

.align 2
nonmatching D_803A9150_ovl8

dlabel D_803A9150_ovl8
    /* 1BB1D0 803A9150 */ .asciz "ATTACK_UPPER"
    /* 41545441434B5F555050455200000000 */
.align 2
enddlabel D_803A9150_ovl8

.align 2
nonmatching D_803A9160_ovl8

dlabel D_803A9160_ovl8
    /* 1BB1E0 803A9160 */ .asciz "ATTACK_LOW"
    /* 41545441434B5F4C4F570000 */
.align 2
enddlabel D_803A9160_ovl8

.align 2
nonmatching D_803A916C_ovl8

dlabel D_803A916C_ovl8
    /* 1BB1EC 803A916C */ .asciz "ATTACK_OVER"
    /* 41545441434B5F4F56455200 */
.align 2
enddlabel D_803A916C_ovl8

.align 2
nonmatching D_803A9178_ovl8

dlabel D_803A9178_ovl8
    /* 1BB1F8 803A9178 */ .asciz "ATTACK_UNDER"
    /* 41545441434B5F554E44455200000000 */
.align 2
enddlabel D_803A9178_ovl8

.align 2
nonmatching D_803A9188_ovl8

dlabel D_803A9188_ovl8
    /* 1BB208 803A9188 */ .asciz "LANDING2"
    /* 4C414E44494E473200000000 */
.align 2
enddlabel D_803A9188_ovl8

.align 2
nonmatching D_803A9194_ovl8

dlabel D_803A9194_ovl8
    /* 1BB214 803A9194 */ .asciz "LANDING1"
    /* 4C414E44494E473100000000 */
.align 2
enddlabel D_803A9194_ovl8

.align 2
nonmatching D_803A91A0_ovl8

dlabel D_803A91A0_ovl8
    /* 1BB220 803A91A0 */ .asciz "ATTACK_SWORD2"
    /* 41545441434B5F53574F524432000000 */
.align 2
enddlabel D_803A91A0_ovl8

.align 2
nonmatching D_803A91B0_ovl8

dlabel D_803A91B0_ovl8
    /* 1BB230 803A91B0 */ .asciz "ATTACK_SWORD1"
    /* 41545441434B5F53574F524431000000 */
.align 2
enddlabel D_803A91B0_ovl8

.align 2
nonmatching D_803A91C0_ovl8

dlabel D_803A91C0_ovl8
    /* 1BB240 803A91C0 */ .asciz "STOP"
    /* 53544F5000000000 */
.align 2
enddlabel D_803A91C0_ovl8

.align 2
nonmatching D_803A91C8_ovl8

dlabel D_803A91C8_ovl8
    /* 1BB248 803A91C8 */ .asciz "ATTACK_2"
    /* 41545441434B5F3200000000 */
.align 2
enddlabel D_803A91C8_ovl8

.align 2
nonmatching D_803A91D4_ovl8

dlabel D_803A91D4_ovl8
    /* 1BB254 803A91D4 */ .asciz "ATTACK_1"
    /* 41545441434B5F3100000000 */
.align 2
enddlabel D_803A91D4_ovl8

.align 2
nonmatching D_803A91E0_ovl8

dlabel D_803A91E0_ovl8
    /* 1BB260 803A91E0 */ .asciz "ENTER_2"
    /* 454E5445525F3200 */
.align 2
enddlabel D_803A91E0_ovl8

.align 2
nonmatching D_803A91E8_ovl8

dlabel D_803A91E8_ovl8
    /* 1BB268 803A91E8 */ .asciz "ENTER_1"
    /* 454E5445525F3100 */
.align 2
enddlabel D_803A91E8_ovl8

.align 2
nonmatching D_803A91F0_ovl8

dlabel D_803A91F0_ovl8
    /* 1BB270 803A91F0 */ .asciz "ENTER_0"
    /* 454E5445525F3000 */
.align 2
.align 2
    /* 1BB278 803A91F8 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 1BB27C 803A91FC */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_803A91F0_ovl8
