.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.39.3 */

.align 3
nonmatching jtbl_803A8BA0_ovl8

dlabel jtbl_803A8BA0_ovl8
    /* 1BAC20 803A8BA0 80391C44 */ .word .L80391C44_ovl8
    /* 1BAC24 803A8BA4 80391BC4 */ .word .L80391BC4_ovl8
    /* 1BAC28 803A8BA8 80391B50 */ .word .L80391B50_ovl8
    /* 1BAC2C 803A8BAC 80391BC4 */ .word .L80391BC4_ovl8
    /* 1BAC30 803A8BB0 80391B50 */ .word .L80391B50_ovl8
    /* 1BAC34 803A8BB4 00000000 */ .word 0x00000000
    /* 1BAC38 803A8BB8 00000000 */ .word 0x00000000
    /* 1BAC3C 803A8BBC 00000000 */ .word 0x00000000
enddlabel jtbl_803A8BA0_ovl8
