.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.39.3 */

nonmatching D_803A9200_ovl8, 0x28

dlabel D_803A9200_ovl8
    /* 803A9200 */ .space 0x28

nonmatching D_803A9228_ovl8, 0x2

dlabel D_803A9228_ovl8
    /* 803A9228 */ .space 0x02

nonmatching D_803A922A_ovl8, 0x2

dlabel D_803A922A_ovl8
    /* 803A922A */ .space 0x02

nonmatching D_803A922C_ovl8, 0x1

dlabel D_803A922C_ovl8
    /* 803A922C */ .space 0x01

nonmatching D_803A922D_ovl8, 0x1

dlabel D_803A922D_ovl8
    /* 803A922D */ .space 0x01

nonmatching D_803A922E_ovl8, 0x2

dlabel D_803A922E_ovl8
    /* 803A922E */ .space 0x02

nonmatching D_803A9230_ovl8, 0x2

dlabel D_803A9230_ovl8
    /* 803A9230 */ .space 0x02

nonmatching D_803A9232_ovl8, 0x2

dlabel D_803A9232_ovl8
    /* 803A9232 */ .space 0x02

nonmatching D_803A9234_ovl8, 0x44

dlabel D_803A9234_ovl8
    /* 803A9234 */ .space 0x44

nonmatching D_803A9278_ovl8, 0x8

dlabel D_803A9278_ovl8
    /* 803A9278 */ .space 0x08

nonmatching D_803A9280_ovl8, 0x2

dlabel D_803A9280_ovl8
    /* 803A9280 */ .space 0x02

nonmatching D_803A9282_ovl8, 0x2

dlabel D_803A9282_ovl8
    /* 803A9282 */ .space 0x02

nonmatching D_803A9284_ovl8, 0x1

dlabel D_803A9284_ovl8
    /* 803A9284 */ .space 0x01

nonmatching D_803A9285_ovl8, 0x1

dlabel D_803A9285_ovl8
    /* 803A9285 */ .space 0x01

nonmatching D_803A9286_ovl8, 0x2

dlabel D_803A9286_ovl8
    /* 803A9286 */ .space 0x02

nonmatching D_803A9288_ovl8, 0x2

dlabel D_803A9288_ovl8
    /* 803A9288 */ .space 0x02

nonmatching D_803A928A_ovl8, 0x1

dlabel D_803A928A_ovl8
    /* 803A928A */ .space 0x01

nonmatching D_803A928B_ovl8, 0xE5

dlabel D_803A928B_ovl8
    /* 803A928B */ .space 0xE5

nonmatching D_803A9370_ovl8, 0x2

dlabel D_803A9370_ovl8
    /* 803A9370 */ .space 0x02

nonmatching D_803A9372_ovl8, 0xE

dlabel D_803A9372_ovl8
    /* 803A9372 */ .space 0x0E

nonmatching D_803A9380_ovl8, 0x10

dlabel D_803A9380_ovl8
    /* 803A9380 */ .space 0x10

nonmatching D_803A9390_ovl8, 0x830

dlabel D_803A9390_ovl8
    /* 803A9390 */ .space 0x830

nonmatching D_803A9BC0_ovl8, 0x4890

dlabel D_803A9BC0_ovl8
    /* 803A9BC0 */ .space 0x4890

nonmatching D_803AE450_ovl8, 0x20

dlabel D_803AE450_ovl8
    /* 803AE450 */ .space 0x20

nonmatching D_803AE470_ovl8, 0x10

dlabel D_803AE470_ovl8
    /* 803AE470 */ .space 0x10

nonmatching D_803AE480_ovl8, 0x4880

dlabel D_803AE480_ovl8
    /* 803AE480 */ .space 0x4880

nonmatching D_803B2D00_ovl8, 0x420

dlabel D_803B2D00_ovl8
    /* 803B2D00 */ .space 0x420

nonmatching D_803B3120_ovl8, 0xC30

dlabel D_803B3120_ovl8
    /* 803B3120 */ .space 0xC30

nonmatching D_803B3D50_ovl8, 0x4

dlabel D_803B3D50_ovl8
    /* 803B3D50 */ .space 0x04

nonmatching D_803B3D54_ovl8, 0x4

dlabel D_803B3D54_ovl8
    /* 803B3D54 */ .space 0x04

nonmatching D_803B3D58_ovl8, 0x4

dlabel D_803B3D58_ovl8
    /* 803B3D58 */ .space 0x04

nonmatching D_803B3D5C_ovl8, 0x4

dlabel D_803B3D5C_ovl8
    /* 803B3D5C */ .space 0x04

nonmatching D_803B3D60_ovl8, 0x4

dlabel D_803B3D60_ovl8
    /* 803B3D60 */ .space 0x04

nonmatching D_803B3D64_ovl8, 0x4

dlabel D_803B3D64_ovl8
    /* 803B3D64 */ .space 0x04

nonmatching D_803B3D68_ovl8, 0x4

dlabel D_803B3D68_ovl8
    /* 803B3D68 */ .space 0x04

nonmatching D_803B3D6C_ovl8, 0x4

dlabel D_803B3D6C_ovl8
    /* 803B3D6C */ .space 0x04

nonmatching D_803B3D70_ovl8, 0x4

dlabel D_803B3D70_ovl8
    /* 803B3D70 */ .space 0x04

nonmatching D_803B3D74_ovl8, 0x4

dlabel D_803B3D74_ovl8
    /* 803B3D74 */ .space 0x04

nonmatching D_803B3D78_ovl8, 0x4

dlabel D_803B3D78_ovl8
    /* 803B3D78 */ .space 0x04

nonmatching D_803B3D7C_ovl8, 0x4

dlabel D_803B3D7C_ovl8
    /* 803B3D7C */ .space 0x04

nonmatching D_803B3D80_ovl8, 0x8

dlabel D_803B3D80_ovl8
    /* 803B3D80 */ .space 0x08

nonmatching D_803B3D88_ovl8, 0x40

dlabel D_803B3D88_ovl8
    /* 803B3D88 */ .space 0x40

nonmatching D_803B3DC8_ovl8, 0x40

dlabel D_803B3DC8_ovl8
    /* 803B3DC8 */ .space 0x40

nonmatching D_803B3E08_ovl8, 0x4

dlabel D_803B3E08_ovl8
    /* 803B3E08 */ .space 0x04

nonmatching D_803B3E0C_ovl8, 0x4

dlabel D_803B3E0C_ovl8
    /* 803B3E0C */ .space 0x04

nonmatching D_803B3E10_ovl8, 0x4

dlabel D_803B3E10_ovl8
    /* 803B3E10 */ .space 0x04

nonmatching D_803B3E14_ovl8, 0xC

dlabel D_803B3E14_ovl8
    /* 803B3E14 */ .space 0x0C

nonmatching D_803B3E20_ovl8, 0x8

dlabel D_803B3E20_ovl8
    /* 803B3E20 */ .space 0x08

nonmatching D_803B3E28_ovl8, 0x4

dlabel D_803B3E28_ovl8
    /* 803B3E28 */ .space 0x04

nonmatching D_803B3E2C_ovl8, 0x4

dlabel D_803B3E2C_ovl8
    /* 803B3E2C */ .space 0x04

nonmatching D_803B3E30_ovl8, 0x4

dlabel D_803B3E30_ovl8
    /* 803B3E30 */ .space 0x04

nonmatching D_803B3E34_ovl8, 0x4

dlabel D_803B3E34_ovl8
    /* 803B3E34 */ .space 0x04

nonmatching D_803B3E38_ovl8, 0x8

dlabel D_803B3E38_ovl8
    /* 803B3E38 */ .space 0x08

nonmatching D_803B3E40_ovl8, 0x4

dlabel D_803B3E40_ovl8
    /* 803B3E40 */ .space 0x04

nonmatching D_803B3E44_ovl8, 0x4

dlabel D_803B3E44_ovl8
    /* 803B3E44 */ .space 0x04

nonmatching D_803B3E48_ovl8, 0x4

dlabel D_803B3E48_ovl8
    /* 803B3E48 */ .space 0x04

nonmatching D_803B3E4C_ovl8, 0x2

dlabel D_803B3E4C_ovl8
    /* 803B3E4C */ .space 0x02

nonmatching D_803B3E4E_ovl8, 0x2

dlabel D_803B3E4E_ovl8
    /* 803B3E4E */ .space 0x02

nonmatching D_803B3E50_ovl8, 0x4

dlabel D_803B3E50_ovl8
    /* 803B3E50 */ .space 0x04

nonmatching D_803B3E54_ovl8, 0x4

dlabel D_803B3E54_ovl8
    /* 803B3E54 */ .space 0x04

nonmatching D_803B3E58_ovl8, 0x4

dlabel D_803B3E58_ovl8
    /* 803B3E58 */ .space 0x04

nonmatching D_803B3E5C_ovl8, 0x2

dlabel D_803B3E5C_ovl8
    /* 803B3E5C */ .space 0x02

nonmatching D_803B3E5E_ovl8, 0x2

dlabel D_803B3E5E_ovl8
    /* 803B3E5E */ .space 0x02

nonmatching D_803B3E60_ovl8, 0x2

dlabel D_803B3E60_ovl8
    /* 803B3E60 */ .space 0x02

nonmatching D_803B3E62_ovl8, 0x6

dlabel D_803B3E62_ovl8
    /* 803B3E62 */ .space 0x06

nonmatching D_803B3E68_ovl8, 0x40

dlabel D_803B3E68_ovl8
    /* 803B3E68 */ .space 0x40

nonmatching D_803B3EA8_ovl8, 0x2

dlabel D_803B3EA8_ovl8
    /* 803B3EA8 */ .space 0x02

nonmatching D_803B3EAA_ovl8, 0x2

dlabel D_803B3EAA_ovl8
    /* 803B3EAA */ .space 0x02

nonmatching D_803B3EAC_ovl8, 0x4

dlabel D_803B3EAC_ovl8
    /* 803B3EAC */ .space 0x04

nonmatching D_803B3EB0_ovl8, 0x4

dlabel D_803B3EB0_ovl8
    /* 803B3EB0 */ .space 0x04

nonmatching D_803B3EB4_ovl8, 0x4

dlabel D_803B3EB4_ovl8
    /* 803B3EB4 */ .space 0x04

nonmatching D_803B3EB8_ovl8, 0x4

dlabel D_803B3EB8_ovl8
    /* 803B3EB8 */ .space 0x04

nonmatching D_803B3EBC_ovl8, 0x4

dlabel D_803B3EBC_ovl8
    /* 803B3EBC */ .space 0x04
