.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.39.3 */

nonmatching D_80069270_ovl3

dlabel D_80069270_ovl3
    /* 112780 80069270 00000000 */ .word 0x00000000
enddlabel D_80069270_ovl3

nonmatching D_80069274_ovl3

dlabel D_80069274_ovl3
    /* 112784 80069274 00000000 */ .word 0x00000000
enddlabel D_80069274_ovl3

nonmatching D_80069278_ovl3

dlabel D_80069278_ovl3
    /* 112788 80069278 00000000 */ .word 0x00000000
enddlabel D_80069278_ovl3

nonmatching D_8006927C_ovl3

dlabel D_8006927C_ovl3
    /* 11278C 8006927C 01000000 */ .word 0x01000000
enddlabel D_8006927C_ovl3
