.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.39.3 */

nonmatching D_800691C0_ovl3

dlabel D_800691C0_ovl3
    /* 1126D0 800691C0 00000000 */ .word 0x00000000
enddlabel D_800691C0_ovl3

nonmatching D_800691C4_ovl3

dlabel D_800691C4_ovl3
    /* 1126D4 800691C4 01000000 */ .word 0x01000000
    /* 1126D8 800691C8 00000000 */ .word 0x00000000
    /* 1126DC 800691CC 00000000 */ .word 0x00000000
enddlabel D_800691C4_ovl3
