.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.39.3 */

nonmatching D_80069790_ovl3

dlabel D_80069790_ovl3
    /* 112CA0 80069790 00000000 */ .word 0x00000000
    /* 112CA4 80069794 00000000 */ .word 0x00000000
enddlabel D_80069790_ovl3

nonmatching D_80069798_ovl3

dlabel D_80069798_ovl3
    /* 112CA8 80069798 00000000 */ .word 0x00000000
enddlabel D_80069798_ovl3

nonmatching D_8006979C_ovl3

dlabel D_8006979C_ovl3
    /* 112CAC 8006979C 00000000 */ .word 0x00000000
enddlabel D_8006979C_ovl3

nonmatching D_800697A0_ovl3

dlabel D_800697A0_ovl3
    /* 112CB0 800697A0 01000000 */ .word 0x01000000
    /* 112CB4 800697A4 00000000 */ .word 0x00000000
    /* 112CB8 800697A8 00000000 */ .word 0x00000000
    /* 112CBC 800697AC 00000000 */ .word 0x00000000
enddlabel D_800697A0_ovl3

nonmatching D_800697B0_ovl3

dlabel D_800697B0_ovl3
    /* 112CC0 800697B0 01000000 */ .word 0x01000000
    /* 112CC4 800697B4 00000000 */ .word 0x00000000
    /* 112CC8 800697B8 00000000 */ .word 0x00000000
    /* 112CCC 800697BC 00000000 */ .word 0x00000000
enddlabel D_800697B0_ovl3

nonmatching D_800697C0_ovl3

dlabel D_800697C0_ovl3
    /* 112CD0 800697C0 00000000 */ .word 0x00000000
enddlabel D_800697C0_ovl3

nonmatching D_800697C4_ovl3

dlabel D_800697C4_ovl3
    /* 112CD4 800697C4 01000000 */ .word 0x01000000
    /* 112CD8 800697C8 00000000 */ .word 0x00000000
    /* 112CDC 800697CC 00000000 */ .word 0x00000000
enddlabel D_800697C4_ovl3

nonmatching D_800697D0_ovl3

dlabel D_800697D0_ovl3
    /* 112CE0 800697D0 01160131 */ .word 0x01160131
    /* 112CE4 800697D4 00D80089 */ .word 0x00D80089
    /* 112CE8 800697D8 009400B6 */ .word 0x009400B6
    /* 112CEC 800697DC 00A700A3 */ .word 0x00A700A3
    /* 112CF0 800697E0 010F00F2 */ .word 0x010F00F2
    /* 112CF4 800697E4 004500E7 */ .word 0x004500E7
    /* 112CF8 800697E8 00BF0001 */ .word 0x00BF0001
    /* 112CFC 800697EC 0036003A */ .word 0x0036003A
    /* 112D00 800697F0 013300E6 */ .word 0x013300E6
    /* 112D04 800697F4 004500C1 */ .word 0x004500C1
    /* 112D08 800697F8 010800AC */ .word 0x010800AC
    /* 112D0C 800697FC 00AD007B */ .word 0x00AD007B
    /* 112D10 80069800 0072006A */ .word 0x0072006A
    /* 112D14 80069804 006C0012 */ .word 0x006C0012
    /* 112D18 80069808 00000000 */ .word 0x00000000
enddlabel D_800697D0_ovl3

nonmatching D_8006980C_ovl3

dlabel D_8006980C_ovl3
    /* 112D1C 8006980C 00390045 */ .word 0x00390045
    /* 112D20 80069810 009700E8 */ .word 0x009700E8
    /* 112D24 80069814 0123014D */ .word 0x0123014D
    /* 112D28 80069818 009E011B */ .word 0x009E011B
    /* 112D2C 8006981C 008E0042 */ .word 0x008E0042
    /* 112D30 80069820 003E0001 */ .word 0x003E0001
    /* 112D34 80069824 00100010 */ .word 0x00100010
    /* 112D38 80069828 009F010E */ .word 0x009F010E
    /* 112D3C 8006982C 006B0068 */ .word 0x006B0068
    /* 112D40 80069830 006C0030 */ .word 0x006C0030
    /* 112D44 80069834 00B80054 */ .word 0x00B80054
    /* 112D48 80069838 0053003E */ .word 0x0053003E
    /* 112D4C 8006983C 002D003A */ .word 0x002D003A
    /* 112D50 80069840 00120000 */ .word 0x00120000
enddlabel D_8006980C_ovl3

nonmatching D_80069844_ovl3

dlabel D_80069844_ovl3
    /* 112D54 80069844 00190010 */ .word 0x00190010
    /* 112D58 80069848 0067005B */ .word 0x0067005B
    /* 112D5C 8006984C 006A006C */ .word 0x006A006C
    /* 112D60 80069850 0058007B */ .word 0x0058007B
    /* 112D64 80069854 0018007C */ .word 0x0018007C
    /* 112D68 80069858 0010001A */ .word 0x0010001A
    /* 112D6C 8006985C 00000000 */ .word 0x00000000
enddlabel D_80069844_ovl3

nonmatching D_80069860_ovl3

dlabel D_80069860_ovl3
    /* 112D70 80069860 01110118 */ .word 0x01110118
    /* 112D74 80069864 00110010 */ .word 0x00110010
    /* 112D78 80069868 00E700B3 */ .word 0x00E700B3
    /* 112D7C 8006986C 0128011C */ .word 0x0128011C
    /* 112D80 80069870 00000000 */ .word 0x00000000
enddlabel D_80069860_ovl3

nonmatching D_80069874_ovl3

dlabel D_80069874_ovl3
    /* 112D84 80069874 014C00E3 */ .word 0x014C00E3
    /* 112D88 80069878 013A008F */ .word 0x013A008F
    /* 112D8C 8006987C 004500A5 */ .word 0x004500A5
    /* 112D90 80069880 0053002C */ .word 0x0053002C
    /* 112D94 80069884 00510012 */ .word 0x00510012
    /* 112D98 80069888 00000000 */ .word 0x00000000
    /* 112D9C 8006988C 00000000 */ .word 0x00000000
    /* 112DA0 80069890 00000000 */ .word 0x00000000
    /* 112DA4 80069894 00000000 */ .word 0x00000000
enddlabel D_80069874_ovl3

nonmatching D_80069898_ovl3

dlabel D_80069898_ovl3
    /* 112DA8 80069898 01000000 */ .word 0x01000000
    /* 112DAC 8006989C 00000000 */ .word 0x00000000
enddlabel D_80069898_ovl3

nonmatching D_800698A0_ovl3

dlabel D_800698A0_ovl3
    /* 112DB0 800698A0 01000100 */ .word 0x01000100
enddlabel D_800698A0_ovl3

nonmatching D_800698A4_ovl3

dlabel D_800698A4_ovl3
    /* 112DB4 800698A4 */ .short 0x0000
enddlabel D_800698A4_ovl3

nonmatching D_800698A6_ovl3

dlabel D_800698A6_ovl3
    /* 112DB6 800698A6 */ .short 0x0000
    /* 112DB8 800698A8 00000225 */ .word 0x00000225
    /* 112DBC 800698AC 3B276471 */ .word 0x3B276471
    /* 112DC0 800698B0 9DF7C77D */ .word 0x9DF7C77D
    /* 112DC4 800698B4 EFFF0000 */ .word 0xEFFF0000
    /* 112DC8 800698B8 00000000 */ .word 0x00000000
    /* 112DCC 800698BC 00000000 */ .word 0x00000000
    /* 112DD0 800698C0 00000000 */ .word 0x00000000
    /* 112DD4 800698C4 00000000 */ .word 0x00000000
    /* 112DD8 800698C8 0000AA01 */ .word 0x0000AA01
    /* 112DDC 800698CC D2C1FBC1 */ .word 0xD2C1FBC1
    /* 112DE0 800698D0 FD0BFE99 */ .word 0xFD0BFE99
    /* 112DE4 800698D4 FFEB0000 */ .word 0xFFEB0000
    /* 112DE8 800698D8 00000000 */ .word 0x00000000
    /* 112DEC 800698DC 00000000 */ .word 0x00000000
    /* 112DF0 800698E0 00000000 */ .word 0x00000000
    /* 112DF4 800698E4 00000000 */ .word 0x00000000
    /* 112DF8 800698E8 00000000 */ .word 0x00000000
    /* 112DFC 800698EC 00000000 */ .word 0x00000000
enddlabel D_800698A6_ovl3

.align 2
nonmatching D_800698F0_ovl3

dlabel D_800698F0_ovl3
    /* 112E00 800698F0 */ .asciz "    TEST      "
    /* 20202020544553542020202020200000 */
.align 2
enddlabel D_800698F0_ovl3

.align 2
nonmatching D_80069900_ovl3

dlabel D_80069900_ovl3
    /* 112E10 80069900 */ .asciz "M:04 DEMO A   "
    /* 4D3A30342044454D4F20412020200000 */
.align 2
enddlabel D_80069900_ovl3

.align 2
nonmatching D_80069910_ovl3

dlabel D_80069910_ovl3
    /* 112E20 80069910 */ .asciz "M:03  CLEAR   "
    /* 4D3A30332020434C4541522020200000 */
.align 2
enddlabel D_80069910_ovl3

.align 2
nonmatching D_80069920_ovl3

dlabel D_80069920_ovl3
    /* 112E30 80069920 */ .asciz "M:03 GAME HARD"
    /* 4D3A30332047414D4520484152440000 */
.align 2
enddlabel D_80069920_ovl3

.align 2
nonmatching D_80069930_ovl3

dlabel D_80069930_ovl3
    /* 112E40 80069930 */ .asciz "M:03 GAME NORM"
    /* 4D3A30332047414D45204E4F524D0000 */
.align 2
enddlabel D_80069930_ovl3

.align 2
nonmatching D_80069940_ovl3

dlabel D_80069940_ovl3
    /* 112E50 80069940 */ .asciz "M:03 GAME EASY"
    /* 4D3A30332047414D4520454153590000 */
.align 2
enddlabel D_80069940_ovl3

.align 2
nonmatching D_80069950_ovl3

dlabel D_80069950_ovl3
    /* 112E60 80069950 */ .asciz "M:03 DEMO A   "
    /* 4D3A30332044454D4F20412020200000 */
.align 2
enddlabel D_80069950_ovl3

.align 2
nonmatching D_80069960_ovl3

dlabel D_80069960_ovl3
    /* 112E70 80069960 */ .asciz "M:02  CLEAR   "
    /* 4D3A30322020434C4541522020200000 */
.align 2
enddlabel D_80069960_ovl3

.align 2
nonmatching D_80069970_ovl3

dlabel D_80069970_ovl3
    /* 112E80 80069970 */ .asciz "M:02 DEMO A   "
    /* 4D3A30322044454D4F20412020200000 */
.align 2
enddlabel D_80069970_ovl3

.align 2
nonmatching D_80069980_ovl3

dlabel D_80069980_ovl3
    /* 112E90 80069980 */ .asciz "M:01  CLEAR   "
    /* 4D3A30312020434C4541522020200000 */
.align 2
enddlabel D_80069980_ovl3

.align 2
nonmatching D_80069990_ovl3

dlabel D_80069990_ovl3
    /* 112EA0 80069990 */ .asciz "M:01 DEMO BC  "
    /* 4D3A30312044454D4F20424320200000 */
.align 2
enddlabel D_80069990_ovl3

.align 2
nonmatching D_800699A0_ovl3

dlabel D_800699A0_ovl3
    /* 112EB0 800699A0 */ .asciz "M:01 DEMO A   "
    /* 4D3A30312044454D4F20412020200000 */
.align 2
enddlabel D_800699A0_ovl3

.align 2
nonmatching D_800699B0_ovl3

dlabel D_800699B0_ovl3
    /* 112EC0 800699B0 */ .asciz "  ADVERTISE   "
    /* 20204144564552544953452020200000 */
.align 2
enddlabel D_800699B0_ovl3

.align 2
nonmatching D_800699C0_ovl3

dlabel D_800699C0_ovl3
    /* 112ED0 800699C0 */ .asciz "   M03 GAME   "
    /* 2020204D30332047414D452020200000 */
.align 2
enddlabel D_800699C0_ovl3

.align 2
nonmatching D_800699D0_ovl3

dlabel D_800699D0_ovl3
    /* 112EE0 800699D0 */ .asciz " OPENING DEMO "
    /* 204F50454E494E472044454D4F200000 */
.align 2
enddlabel D_800699D0_ovl3

.align 2
nonmatching D_800699E0_ovl3

dlabel D_800699E0_ovl3
    /* 112EF0 800699E0 */ .asciz " THIRD IMPACT "
    /* 20544849524420494D50414354200000 */
.align 2
enddlabel D_800699E0_ovl3

.align 2
nonmatching D_800699F0_ovl3

dlabel D_800699F0_ovl3
    /* 112F00 800699F0 */ .asciz "  SOUND TEST  "
    /* 2020534F554E44205445535420200000 */
.align 2
enddlabel D_800699F0_ovl3

.align 2
nonmatching D_80069A00_ovl3

dlabel D_80069A00_ovl3
    /* 112F10 80069A00 */ .asciz " SIMULAT MENU "
    /* 2053494D554C4154204D454E55200000 */
.align 2
enddlabel D_80069A00_ovl3

.align 2
nonmatching D_80069A10_ovl3

dlabel D_80069A10_ovl3
    /* 112F20 80069A10 */ .asciz " OPTION  MENU "
    /* 204F5054494F4E20204D454E55200000 */
.align 2
enddlabel D_80069A10_ovl3

.align 2
nonmatching D_80069A20_ovl3

dlabel D_80069A20_ovl3
    /* 112F30 80069A20 */ .asciz " STORY   MENU "
    /* 2053544F52592020204D454E55200000 */
.align 2
enddlabel D_80069A20_ovl3

.align 2
nonmatching D_80069A30_ovl3

dlabel D_80069A30_ovl3
    /* 112F40 80069A30 */ .asciz "  MAIN MENU   "
    /* 20204D41494E204D454E552020200000 */
.align 2
enddlabel D_80069A30_ovl3

.align 2
nonmatching D_80069A40_ovl3

dlabel D_80069A40_ovl3
    /* 112F50 80069A40 */ .asciz "  SECTION 3   "
    /* 202053454354494F4E20332020200000 */
.align 2
enddlabel D_80069A40_ovl3

.align 2
nonmatching D_80069A50_ovl3

dlabel D_80069A50_ovl3
    /* 112F60 80069A50 */ .asciz "  GAME OVER   "
    /* 202047414D45204F5645522020200000 */
.align 2
enddlabel D_80069A50_ovl3

.align 2
nonmatching D_80069A60_ovl3

dlabel D_80069A60_ovl3
    /* 112F70 80069A60 */ .asciz "   CONTINUE   "
    /* 202020434F4E54494E55452020200000 */
.align 2
enddlabel D_80069A60_ovl3

.align 2
nonmatching D_80069A70_ovl3

dlabel D_80069A70_ovl3
    /* 112F80 80069A70 */ .asciz "  EYE  CATCH  "
    /* 20204559452020434154434820200000 */
.align 2
enddlabel D_80069A70_ovl3

.align 2
nonmatching D_80069A80_ovl3

dlabel D_80069A80_ovl3
    /* 112F90 80069A80 */ .asciz "  IN   CATCH  "
    /* 2020494E202020434154434820200000 */
.align 2
enddlabel D_80069A80_ovl3

.align 2
nonmatching D_80069A90_ovl3

dlabel D_80069A90_ovl3
    /* 112FA0 80069A90 */ .asciz "  SAVE SELECT "
    /* 2020534156452053454C454354200000 */
.align 2
enddlabel D_80069A90_ovl3

.align 2
nonmatching D_80069AA0_ovl3

dlabel D_80069AA0_ovl3
    /* 112FB0 80069AA0 */ .asciz "  COPY RIGHT  "
    /* 2020434F505920524947485420200000 */
.align 2
enddlabel D_80069AA0_ovl3

.align 2
nonmatching D_80069AB0_ovl3

dlabel D_80069AB0_ovl3
    /* 112FC0 80069AB0 */ .asciz "  DEMO TEST   "
    /* 202044454D4F20544553542020200000 */
.align 2
enddlabel D_80069AB0_ovl3

.align 2
nonmatching D_80069AC0_ovl3

dlabel D_80069AC0_ovl3
    /* 112FD0 80069AC0 */ .asciz "NA2 TEST"
    /* 4E4132205445535400000000 */
.align 2
.align 2
    /* 112FDC 80069ACC */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_80069AC0_ovl3

nonmatching jtbl_80069AD0_ovl3

dlabel jtbl_80069AD0_ovl3
    /* 112FE0 80069AD0 80025C30 */ .word 0x80025C30
    /* 112FE4 80069AD4 80025C5C */ .word 0x80025C5C
    /* 112FE8 80069AD8 80025CA8 */ .word 0x80025CA8
    /* 112FEC 80069ADC 80025D14 */ .word 0x80025D14
    /* 112FF0 80069AE0 80025D38 */ .word 0x80025D38
    /* 112FF4 80069AE4 00000000 */ .word 0x00000000
enddlabel jtbl_80069AD0_ovl3

nonmatching jtbl_80069AE8_ovl3

dlabel jtbl_80069AE8_ovl3
    /* 112FF8 80069AE8 80026EB8 */ .word 0x80026EB8
    /* 112FFC 80069AEC 80026F04 */ .word 0x80026F04
    /* 113000 80069AF0 80026F7C */ .word 0x80026F7C
    /* 113004 80069AF4 80027080 */ .word 0x80027080
    /* 113008 80069AF8 800271BC */ .word 0x800271BC
    /* 11300C 80069AFC 80027250 */ .word 0x80027250
    /* 113010 80069B00 800272E8 */ .word 0x800272E8
    /* 113014 80069B04 80027E94 */ .word 0x80027E94
    /* 113018 80069B08 00000000 */ .word 0x00000000
    /* 11301C 80069B0C 00000000 */ .word 0x00000000
enddlabel jtbl_80069AE8_ovl3

.align 3
nonmatching D_80069B10_ovl3

dlabel D_80069B10_ovl3
    /* 113020 80069B10 3FF8000000000000 */ .double 1.5
    /* 113028 80069B18 0000000000000000 */ .double 0
enddlabel D_80069B10_ovl3

nonmatching jtbl_80069B20_ovl3

dlabel jtbl_80069B20_ovl3
    /* 113030 80069B20 80028740 */ .word 0x80028740
    /* 113034 80069B24 8002876C */ .word 0x8002876C
    /* 113038 80069B28 80028958 */ .word 0x80028958
    /* 11303C 80069B2C 8002893C */ .word 0x8002893C
    /* 113040 80069B30 800289DC */ .word 0x800289DC
    /* 113044 80069B34 80028A50 */ .word 0x80028A50
    /* 113048 80069B38 00000000 */ .word 0x00000000
    /* 11304C 80069B3C 00000000 */ .word 0x00000000
enddlabel jtbl_80069B20_ovl3

.align 3
nonmatching D_80069B40_ovl3

dlabel D_80069B40_ovl3
    /* 113050 80069B40 3FE0000000000000 */ .double 0.5
    /* 113058 80069B48 0000000000000000 */ .double 0
enddlabel D_80069B40_ovl3

.align 3
nonmatching D_80069B50_ovl3

dlabel D_80069B50_ovl3
    /* 113060 80069B50 3FF8000000000000 */ .double 1.5
enddlabel D_80069B50_ovl3

.align 3
nonmatching D_80069B58_ovl3

dlabel D_80069B58_ovl3
    /* 113068 80069B58 41E0000000000000 */ .double 2147483648
enddlabel D_80069B58_ovl3

.align 3
nonmatching D_80069B60_ovl3

dlabel D_80069B60_ovl3
    /* 113070 80069B60 3FF8000000000000 */ .double 1.5
    /* 113078 80069B68 0000000000000000 */ .double 0
enddlabel D_80069B60_ovl3

nonmatching jtbl_80069B70_ovl3

dlabel jtbl_80069B70_ovl3
    /* 113080 80069B70 8002A418 */ .word 0x8002A418
    /* 113084 80069B74 8002A428 */ .word 0x8002A428
    /* 113088 80069B78 8002A438 */ .word 0x8002A438
    /* 11308C 80069B7C 8002A448 */ .word 0x8002A448
    /* 113090 80069B80 8002A45C */ .word 0x8002A45C
    /* 113094 80069B84 8002A470 */ .word 0x8002A470
    /* 113098 80069B88 8002A484 */ .word 0x8002A484
    /* 11309C 80069B8C 8002A498 */ .word 0x8002A498
    /* 1130A0 80069B90 8002A4AC */ .word 0x8002A4AC
    /* 1130A4 80069B94 00000000 */ .word 0x00000000
    /* 1130A8 80069B98 00000000 */ .word 0x00000000
    /* 1130AC 80069B9C 00000000 */ .word 0x00000000
enddlabel jtbl_80069B70_ovl3

.align 2
nonmatching D_80069BA0_ovl3

dlabel D_80069BA0_ovl3
    /* 1130B0 80069BA0 */ .asciz "no2"
    /* 6E6F3200 */
.align 2
enddlabel D_80069BA0_ovl3

.align 2
nonmatching D_80069BA4_ovl3

dlabel D_80069BA4_ovl3
    /* 1130B4 80069BA4 */ .asciz "no1"
    /* 6E6F3100 */
.align 2
enddlabel D_80069BA4_ovl3

.align 2
nonmatching D_80069BA8_ovl3

dlabel D_80069BA8_ovl3
    /* 1130B8 80069BA8 */ .asciz "no0"
    /* 6E6F3000 */
.align 2
.align 2
    /* 1130BC 80069BAC */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_80069BA8_ovl3

.align 3
nonmatching D_80069BB0_ovl3

dlabel D_80069BB0_ovl3
    /* 1130C0 80069BB0 3FE0000000000000 */ .double 0.5
enddlabel D_80069BB0_ovl3

.align 3
nonmatching D_80069BB8_ovl3

dlabel D_80069BB8_ovl3
    /* 1130C8 80069BB8 41E0000000000000 */ .double 2147483648
enddlabel D_80069BB8_ovl3

.align 3
nonmatching D_80069BC0_ovl3

dlabel D_80069BC0_ovl3
    /* 1130D0 80069BC0 3FE0000000000000 */ .double 0.5
enddlabel D_80069BC0_ovl3

.align 3
nonmatching D_80069BC8_ovl3

dlabel D_80069BC8_ovl3
    /* 1130D8 80069BC8 41E0000000000000 */ .double 2147483648
enddlabel D_80069BC8_ovl3

.align 3
nonmatching D_80069BD0_ovl3

dlabel D_80069BD0_ovl3
    /* 1130E0 80069BD0 3F91DF46A2529D39 */ .double 0.0174532925199432955
    /* 1130E8 80069BD8 0000000000000000 */ .double 0
enddlabel D_80069BD0_ovl3

.align 3
nonmatching D_80069BE0_ovl3

dlabel D_80069BE0_ovl3
    /* 1130F0 80069BE0 3FF8000000000000 */ .double 1.5
enddlabel D_80069BE0_ovl3

.align 3
nonmatching D_80069BE8_ovl3

dlabel D_80069BE8_ovl3
    /* 1130F8 80069BE8 4075600000000000 */ .double 342
enddlabel D_80069BE8_ovl3

.align 3
nonmatching D_80069BF0_ovl3

dlabel D_80069BF0_ovl3
    /* 113100 80069BF0 4082000000000000 */ .double 576
enddlabel D_80069BF0_ovl3

.align 3
nonmatching D_80069BF8_ovl3

dlabel D_80069BF8_ovl3
    /* 113108 80069BF8 3FF0000000000000 */ .double 1
enddlabel D_80069BF8_ovl3

nonmatching jtbl_80069C00_ovl3

dlabel jtbl_80069C00_ovl3
    /* 113110 80069C00 8002D9E8 */ .word 0x8002D9E8
    /* 113114 80069C04 8002DA30 */ .word 0x8002DA30
    /* 113118 80069C08 8002DC10 */ .word 0x8002DC10
    /* 11311C 80069C0C 8002DFA4 */ .word 0x8002DFA4
    /* 113120 80069C10 8002E0F4 */ .word 0x8002E0F4
    /* 113124 80069C14 8002E170 */ .word 0x8002E170
    /* 113128 80069C18 8002E198 */ .word 0x8002E198
    /* 11312C 80069C1C 00000000 */ .word 0x00000000
enddlabel jtbl_80069C00_ovl3

.align 3
nonmatching D_80069C20_ovl3

dlabel D_80069C20_ovl3
    /* 113130 80069C20 3FF8000000000000 */ .double 1.5
enddlabel D_80069C20_ovl3

.align 3
nonmatching D_80069C28_ovl3

dlabel D_80069C28_ovl3
    /* 113138 80069C28 3FF8000000000000 */ .double 1.5
enddlabel D_80069C28_ovl3

.align 3
nonmatching D_80069C30_ovl3

dlabel D_80069C30_ovl3
    /* 113140 80069C30 4075600000000000 */ .double 342
enddlabel D_80069C30_ovl3

.align 3
nonmatching D_80069C38_ovl3

dlabel D_80069C38_ovl3
    /* 113148 80069C38 4082000000000000 */ .double 576
enddlabel D_80069C38_ovl3

.align 3
nonmatching D_80069C40_ovl3

dlabel D_80069C40_ovl3
    /* 113150 80069C40 3FF0000000000000 */ .double 1
    /* 113158 80069C48 0000000000000000 */ .double 0
enddlabel D_80069C40_ovl3

nonmatching jtbl_80069C50_ovl3

dlabel jtbl_80069C50_ovl3
    /* 113160 80069C50 8002EA34 */ .word 0x8002EA34
    /* 113164 80069C54 8002EA84 */ .word 0x8002EA84
    /* 113168 80069C58 8002EB60 */ .word 0x8002EB60
    /* 11316C 80069C5C 8002EF24 */ .word 0x8002EF24
    /* 113170 80069C60 8002EE9C */ .word 0x8002EE9C
    /* 113174 80069C64 8002EC54 */ .word 0x8002EC54
    /* 113178 80069C68 8002EF78 */ .word 0x8002EF78
    /* 11317C 80069C6C 8002F330 */ .word 0x8002F330
enddlabel jtbl_80069C50_ovl3

.align 3
nonmatching D_80069C70_ovl3

dlabel D_80069C70_ovl3
    /* 113180 80069C70 3FE0000000000000 */ .double 0.5
enddlabel D_80069C70_ovl3

.align 3
nonmatching D_80069C78_ovl3

dlabel D_80069C78_ovl3
    /* 113188 80069C78 3FE0000000000000 */ .double 0.5
enddlabel D_80069C78_ovl3

.align 3
nonmatching D_80069C80_ovl3

dlabel D_80069C80_ovl3
    /* 113190 80069C80 3FB999999999999A */ .double 0.100000000000000006
enddlabel D_80069C80_ovl3

.align 3
nonmatching D_80069C88_ovl3

dlabel D_80069C88_ovl3
    /* 113198 80069C88 404CA5DC1A63C1F8 */ .double 57.2957795130823229
enddlabel D_80069C88_ovl3

.align 3
nonmatching D_80069C90_ovl3

dlabel D_80069C90_ovl3
    /* 1131A0 80069C90 3F91DF46A2529D39 */ .double 0.0174532925199432955
enddlabel D_80069C90_ovl3

.align 3
nonmatching D_80069C98_ovl3

dlabel D_80069C98_ovl3
    /* 1131A8 80069C98 404CA5DC1A63C1F8 */ .double 57.2957795130823229
enddlabel D_80069C98_ovl3

.align 3
nonmatching D_80069CA0_ovl3

dlabel D_80069CA0_ovl3
    /* 1131B0 80069CA0 3F91DF46A2529D39 */ .double 0.0174532925199432955
enddlabel D_80069CA0_ovl3

.align 3
nonmatching D_80069CA8_ovl3

dlabel D_80069CA8_ovl3
    /* 1131B8 80069CA8 3FD999999999999A */ .double 0.400000000000000022
enddlabel D_80069CA8_ovl3

.align 3
nonmatching D_80069CB0_ovl3

dlabel D_80069CB0_ovl3
    /* 1131C0 80069CB0 3FE0000000000000 */ .double 0.5
enddlabel D_80069CB0_ovl3

.align 3
nonmatching D_80069CB8_ovl3

dlabel D_80069CB8_ovl3
    /* 1131C8 80069CB8 3FE0000000000000 */ .double 0.5
enddlabel D_80069CB8_ovl3

.align 3
nonmatching D_80069CC0_ovl3

dlabel D_80069CC0_ovl3
    /* 1131D0 80069CC0 3F91DF46A2529D39 */ .double 0.0174532925199432955
enddlabel D_80069CC0_ovl3

.align 2
nonmatching D_80069CC8_ovl3

dlabel D_80069CC8_ovl3
    /* 1131D8 80069CC8 */ .asciz "lfoot3"
    /* 6C666F6F74330000 */
.align 2
enddlabel D_80069CC8_ovl3

.align 2
nonmatching D_80069CD0_ovl3

dlabel D_80069CD0_ovl3
    /* 1131E0 80069CD0 */ .asciz "lfoot2"
    /* 6C666F6F74320000 */
.align 2
enddlabel D_80069CD0_ovl3

.align 2
nonmatching D_80069CD8_ovl3

dlabel D_80069CD8_ovl3
    /* 1131E8 80069CD8 */ .asciz "lfoot1"
    /* 6C666F6F74310000 */
.align 2
enddlabel D_80069CD8_ovl3

.align 2
nonmatching D_80069CE0_ovl3

dlabel D_80069CE0_ovl3
    /* 1131F0 80069CE0 */ .asciz "lhand"
    /* 6C68616E64000000 */
.align 2
enddlabel D_80069CE0_ovl3

.align 2
nonmatching D_80069CE8_ovl3

dlabel D_80069CE8_ovl3
    /* 1131F8 80069CE8 */ .asciz "larm2"
    /* 6C61726D32000000 */
.align 2
enddlabel D_80069CE8_ovl3

.align 2
nonmatching D_80069CF0_ovl3

dlabel D_80069CF0_ovl3
    /* 113200 80069CF0 */ .asciz "larm1"
    /* 6C61726D31000000 */
.align 2
enddlabel D_80069CF0_ovl3

.align 2
nonmatching D_80069CF8_ovl3

dlabel D_80069CF8_ovl3
    /* 113208 80069CF8 */ .asciz "face1"
    /* 6661636531000000 */
.align 2
enddlabel D_80069CF8_ovl3

.align 2
nonmatching D_80069D00_ovl3

dlabel D_80069D00_ovl3
    /* 113210 80069D00 */ .asciz "body3"
    /* 626F647933000000 */
.align 2
enddlabel D_80069D00_ovl3

.align 2
nonmatching D_80069D08_ovl3

dlabel D_80069D08_ovl3
    /* 113218 80069D08 */ .asciz "body2"
    /* 626F647932000000 */
.align 2
enddlabel D_80069D08_ovl3

.align 2
nonmatching D_80069D10_ovl3

dlabel D_80069D10_ovl3
    /* 113220 80069D10 */ .asciz "body1"
    /* 626F647931000000 */
.align 2
.align 2
    /* 113228 80069D18 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 11322C 80069D1C */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_80069D10_ovl3

.align 3
nonmatching D_80069D20_ovl3

dlabel D_80069D20_ovl3
    /* 113230 80069D20 402E000000000000 */ .double 15
enddlabel D_80069D20_ovl3

.align 3
nonmatching D_80069D28_ovl3

dlabel D_80069D28_ovl3
    /* 113238 80069D28 402E000000000000 */ .double 15
enddlabel D_80069D28_ovl3

.align 3
nonmatching D_80069D30_ovl3

dlabel D_80069D30_ovl3
    /* 113240 80069D30 3FD3333333333333 */ .double 0.299999999999999989
enddlabel D_80069D30_ovl3

.align 3
nonmatching D_80069D38_ovl3

dlabel D_80069D38_ovl3
    /* 113248 80069D38 3FF4CCCCCCCCCCCD */ .double 1.30000000000000004
enddlabel D_80069D38_ovl3

.align 3
nonmatching D_80069D40_ovl3

dlabel D_80069D40_ovl3
    /* 113250 80069D40 3FE0000000000000 */ .double 0.5
enddlabel D_80069D40_ovl3

.align 3
nonmatching D_80069D48_ovl3

dlabel D_80069D48_ovl3
    /* 113258 80069D48 3FD999999999999A */ .double 0.400000000000000022
enddlabel D_80069D48_ovl3

.align 3
nonmatching D_80069D50_ovl3

dlabel D_80069D50_ovl3
    /* 113260 80069D50 3F847AE147AE147B */ .double 0.0100000000000000002
enddlabel D_80069D50_ovl3

.align 3
nonmatching D_80069D58_ovl3

dlabel D_80069D58_ovl3
    /* 113268 80069D58 3F847AE147AE147B */ .double 0.0100000000000000002
enddlabel D_80069D58_ovl3

.align 3
nonmatching D_80069D60_ovl3

dlabel D_80069D60_ovl3
    /* 113270 80069D60 3FD999999999999A */ .double 0.400000000000000022
enddlabel D_80069D60_ovl3

.align 3
nonmatching D_80069D68_ovl3

dlabel D_80069D68_ovl3
    /* 113278 80069D68 3FD999999999999A */ .double 0.400000000000000022
enddlabel D_80069D68_ovl3

.align 3
nonmatching D_80069D70_ovl3

dlabel D_80069D70_ovl3
    /* 113280 80069D70 3FD999999999999A */ .double 0.400000000000000022
enddlabel D_80069D70_ovl3

.align 2
nonmatching D_80069D78_ovl3

dlabel D_80069D78_ovl3
    /* 113288 80069D78 */ .asciz "pt00"
    /* 7074303000000000 */
.align 2
enddlabel D_80069D78_ovl3

.align 2
nonmatching D_80069D80_ovl3

dlabel D_80069D80_ovl3
    /* 113290 80069D80 */ .asciz "bom00"
    /* 626F6D3030000000 */
.align 2
.align 2
    /* 113298 80069D88 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 11329C 80069D8C */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_80069D80_ovl3

.align 2
nonmatching D_80069D90_ovl3

dlabel D_80069D90_ovl3
    /* 1132A0 80069D90 */ .asciz "DEM:"
    /* 44454D3A00000000 */
.align 2
enddlabel D_80069D90_ovl3

nonmatching D_80069D98_ovl3

dlabel D_80069D98_ovl3
    /* 1132A8 80069D98 00000000 */ .word 0x00000000
    /* 1132AC 80069D9C 00000000 */ .word 0x00000000
enddlabel D_80069D98_ovl3

nonmatching jtbl_80069DA0_ovl3

dlabel jtbl_80069DA0_ovl3
    /* 1132B0 80069DA0 800365CC */ .word 0x800365CC
    /* 1132B4 80069DA4 8003651C */ .word 0x8003651C
    /* 1132B8 80069DA8 8003653C */ .word 0x8003653C
    /* 1132BC 80069DAC 8003653C */ .word 0x8003653C
    /* 1132C0 80069DB0 8003653C */ .word 0x8003653C
    /* 1132C4 80069DB4 80036570 */ .word 0x80036570
    /* 1132C8 80069DB8 800365A0 */ .word 0x800365A0
    /* 1132CC 80069DBC 00000000 */ .word 0x00000000
enddlabel jtbl_80069DA0_ovl3

nonmatching jtbl_80069DC0_ovl3

dlabel jtbl_80069DC0_ovl3
    /* 1132D0 80069DC0 8003673C */ .word 0x8003673C
    /* 1132D4 80069DC4 80036694 */ .word 0x80036694
    /* 1132D8 80069DC8 800366B4 */ .word 0x800366B4
    /* 1132DC 80069DCC 800366B4 */ .word 0x800366B4
    /* 1132E0 80069DD0 800366B4 */ .word 0x800366B4
    /* 1132E4 80069DD4 800366E0 */ .word 0x800366E0
    /* 1132E8 80069DD8 80036710 */ .word 0x80036710
    /* 1132EC 80069DDC 00000000 */ .word 0x00000000
enddlabel jtbl_80069DC0_ovl3

nonmatching jtbl_80069DE0_ovl3

dlabel jtbl_80069DE0_ovl3
    /* 1132F0 80069DE0 800372E8 */ .word 0x800372E8
    /* 1132F4 80069DE4 80037304 */ .word 0x80037304
    /* 1132F8 80069DE8 80037334 */ .word 0x80037334
    /* 1132FC 80069DEC 80037348 */ .word 0x80037348
    /* 113300 80069DF0 8003735C */ .word 0x8003735C
    /* 113304 80069DF4 800373AC */ .word 0x800373AC
    /* 113308 80069DF8 800373E8 */ .word 0x800373E8
    /* 11330C 80069DFC 00000000 */ .word 0x00000000
enddlabel jtbl_80069DE0_ovl3

nonmatching jtbl_80069E00_ovl3

dlabel jtbl_80069E00_ovl3
    /* 113310 80069E00 80037568 */ .word 0x80037568
    /* 113314 80069E04 80037584 */ .word 0x80037584
    /* 113318 80069E08 800375C0 */ .word 0x800375C0
    /* 11331C 80069E0C 800375D4 */ .word 0x800375D4
    /* 113320 80069E10 800375E8 */ .word 0x800375E8
    /* 113324 80069E14 80037638 */ .word 0x80037638
    /* 113328 80069E18 80037680 */ .word 0x80037680
    /* 11332C 80069E1C 00000000 */ .word 0x00000000
enddlabel jtbl_80069E00_ovl3

nonmatching jtbl_80069E20_ovl3

dlabel jtbl_80069E20_ovl3
    /* 113330 80069E20 80037910 */ .word 0x80037910
    /* 113334 80069E24 80037910 */ .word 0x80037910
    /* 113338 80069E28 80037920 */ .word 0x80037920
    /* 11333C 80069E2C 80037920 */ .word 0x80037920
    /* 113340 80069E30 80037920 */ .word 0x80037920
    /* 113344 80069E34 80037934 */ .word 0x80037934
    /* 113348 80069E38 80037934 */ .word 0x80037934
    /* 11334C 80069E3C 00000000 */ .word 0x00000000
enddlabel jtbl_80069E20_ovl3

nonmatching jtbl_80069E40_ovl3

dlabel jtbl_80069E40_ovl3
    /* 113350 80069E40 80037974 */ .word 0x80037974
    /* 113354 80069E44 80037974 */ .word 0x80037974
    /* 113358 80069E48 80037984 */ .word 0x80037984
    /* 11335C 80069E4C 80037984 */ .word 0x80037984
    /* 113360 80069E50 80037984 */ .word 0x80037984
    /* 113364 80069E54 80037998 */ .word 0x80037998
    /* 113368 80069E58 80037998 */ .word 0x80037998
    /* 11336C 80069E5C 00000000 */ .word 0x00000000
enddlabel jtbl_80069E40_ovl3
