.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.39.3 */

nonmatching D_8006A600_ovl3, 0x4

dlabel D_8006A600_ovl3
    /* 8006A600 */ .space 0x04

nonmatching D_8006A604_ovl3, 0xC

dlabel D_8006A604_ovl3
    /* 8006A604 */ .space 0x0C

nonmatching D_8006A610_ovl3, 0x2

dlabel D_8006A610_ovl3
    /* 8006A610 */ .space 0x02

nonmatching D_8006A612_ovl3, 0x2

dlabel D_8006A612_ovl3
    /* 8006A612 */ .space 0x02

nonmatching D_8006A614_ovl3, 0x1

dlabel D_8006A614_ovl3
    /* 8006A614 */ .space 0x01

nonmatching D_8006A615_ovl3, 0x1

dlabel D_8006A615_ovl3
    /* 8006A615 */ .space 0x01

nonmatching D_8006A616_ovl3, 0x2

dlabel D_8006A616_ovl3
    /* 8006A616 */ .space 0x02

nonmatching D_8006A618_ovl3, 0x2

dlabel D_8006A618_ovl3
    /* 8006A618 */ .space 0x02

nonmatching D_8006A61A_ovl3, 0x2

dlabel D_8006A61A_ovl3
    /* 8006A61A */ .space 0x02

nonmatching D_8006A61C_ovl3, 0x4

dlabel D_8006A61C_ovl3
    /* 8006A61C */ .space 0x04

nonmatching D_8006A620_ovl3, 0x3

dlabel D_8006A620_ovl3
    /* 8006A620 */ .space 0x03

nonmatching D_8006A623_ovl3, 0x1

dlabel D_8006A623_ovl3
    /* 8006A623 */ .space 0x01

nonmatching D_8006A624_ovl3, 0xC

dlabel D_8006A624_ovl3
    /* 8006A624 */ .space 0x0C

nonmatching D_8006A630_ovl3, 0x2

dlabel D_8006A630_ovl3
    /* 8006A630 */ .space 0x02

nonmatching D_8006A632_ovl3, 0xE

dlabel D_8006A632_ovl3
    /* 8006A632 */ .space 0x0E

nonmatching D_8006A640_ovl3, 0x1900

dlabel D_8006A640_ovl3
    /* 8006A640 */ .space 0x1900

nonmatching D_8006BF40_ovl3, 0x40

dlabel D_8006BF40_ovl3
    /* 8006BF40 */ .space 0x40

nonmatching D_8006BF80_ovl3, 0x4

dlabel D_8006BF80_ovl3
    /* 8006BF80 */ .space 0x04

nonmatching D_8006BF84_ovl3, 0x4

dlabel D_8006BF84_ovl3
    /* 8006BF84 */ .space 0x04

nonmatching D_8006BF88_ovl3, 0x4

dlabel D_8006BF88_ovl3
    /* 8006BF88 */ .space 0x04

nonmatching D_8006BF8C_ovl3, 0x4

dlabel D_8006BF8C_ovl3
    /* 8006BF8C */ .space 0x04

nonmatching D_8006BF90_ovl3, 0x4

dlabel D_8006BF90_ovl3
    /* 8006BF90 */ .space 0x04

nonmatching D_8006BF94_ovl3, 0x4

dlabel D_8006BF94_ovl3
    /* 8006BF94 */ .space 0x04

nonmatching D_8006BF98_ovl3, 0x4

dlabel D_8006BF98_ovl3
    /* 8006BF98 */ .space 0x04

nonmatching D_8006BF9C_ovl3, 0x4

dlabel D_8006BF9C_ovl3
    /* 8006BF9C */ .space 0x04

nonmatching D_8006BFA0_ovl3, 0x4

dlabel D_8006BFA0_ovl3
    /* 8006BFA0 */ .space 0x04

nonmatching D_8006BFA4_ovl3, 0x4

dlabel D_8006BFA4_ovl3
    /* 8006BFA4 */ .space 0x04

nonmatching D_8006BFA8_ovl3, 0x2

dlabel D_8006BFA8_ovl3
    /* 8006BFA8 */ .space 0x02

nonmatching D_8006BFAA_ovl3, 0x1

dlabel D_8006BFAA_ovl3
    /* 8006BFAA */ .space 0x01

nonmatching D_8006BFAB_ovl3, 0x1

dlabel D_8006BFAB_ovl3
    /* 8006BFAB */ .space 0x01

nonmatching D_8006BFAC_ovl3, 0x4

dlabel D_8006BFAC_ovl3
    /* 8006BFAC */ .space 0x04

nonmatching D_8006BFB0_ovl3, 0x4

dlabel D_8006BFB0_ovl3
    /* 8006BFB0 */ .space 0x04

nonmatching D_8006BFB4_ovl3, 0x4

dlabel D_8006BFB4_ovl3
    /* 8006BFB4 */ .space 0x04

nonmatching D_8006BFB8_ovl3, 0x4

dlabel D_8006BFB8_ovl3
    /* 8006BFB8 */ .space 0x04

nonmatching D_8006BFBC_ovl3, 0x4

dlabel D_8006BFBC_ovl3
    /* 8006BFBC */ .space 0x04

nonmatching D_8006BFC0_ovl3, 0x8

dlabel D_8006BFC0_ovl3
    /* 8006BFC0 */ .space 0x08

nonmatching D_8006BFC8_ovl3, 0x2

dlabel D_8006BFC8_ovl3
    /* 8006BFC8 */ .space 0x02

nonmatching D_8006BFCA_ovl3, 0x6

dlabel D_8006BFCA_ovl3
    /* 8006BFCA */ .space 0x06

nonmatching D_8006BFD0_ovl3, 0x4

dlabel D_8006BFD0_ovl3
    /* 8006BFD0 */ .space 0x04

nonmatching D_8006BFD4_ovl3, 0x4

dlabel D_8006BFD4_ovl3
    /* 8006BFD4 */ .space 0x04

nonmatching D_8006BFD8_ovl3, 0x4

dlabel D_8006BFD8_ovl3
    /* 8006BFD8 */ .space 0x04

nonmatching D_8006BFDC_ovl3, 0x8

dlabel D_8006BFDC_ovl3
    /* 8006BFDC */ .space 0x08

nonmatching D_8006BFE4_ovl3, 0xC

dlabel D_8006BFE4_ovl3
    /* 8006BFE4 */ .space 0x0C

nonmatching D_8006BFF0_ovl3, 0x14

dlabel D_8006BFF0_ovl3
    /* 8006BFF0 */ .space 0x14

nonmatching D_8006C004_ovl3, 0x4

dlabel D_8006C004_ovl3
    /* 8006C004 */ .space 0x04

nonmatching D_8006C008_ovl3, 0x8

dlabel D_8006C008_ovl3
    /* 8006C008 */ .space 0x08

nonmatching D_8006C010_ovl3, 0x4

dlabel D_8006C010_ovl3
    /* 8006C010 */ .space 0x04

nonmatching D_8006C014_ovl3, 0x10

dlabel D_8006C014_ovl3
    /* 8006C014 */ .space 0x10

nonmatching D_8006C024_ovl3, 0x4

dlabel D_8006C024_ovl3
    /* 8006C024 */ .space 0x04

nonmatching D_8006C028_ovl3, 0x4

dlabel D_8006C028_ovl3
    /* 8006C028 */ .space 0x04

nonmatching D_8006C02C_ovl3, 0x4

dlabel D_8006C02C_ovl3
    /* 8006C02C */ .space 0x04

nonmatching D_8006C030_ovl3, 0x4

dlabel D_8006C030_ovl3
    /* 8006C030 */ .space 0x04

nonmatching D_8006C034_ovl3, 0x6

dlabel D_8006C034_ovl3
    /* 8006C034 */ .space 0x06

nonmatching D_8006C03A_ovl3, 0x6

dlabel D_8006C03A_ovl3
    /* 8006C03A */ .space 0x06

nonmatching D_8006C040_ovl3, 0x20

dlabel D_8006C040_ovl3
    /* 8006C040 */ .space 0x20

nonmatching D_8006C060_ovl3, 0x4

dlabel D_8006C060_ovl3
    /* 8006C060 */ .space 0x04

nonmatching D_8006C064_ovl3, 0x4

dlabel D_8006C064_ovl3
    /* 8006C064 */ .space 0x04

nonmatching D_8006C068_ovl3, 0x4

dlabel D_8006C068_ovl3
    /* 8006C068 */ .space 0x04

nonmatching D_8006C06C_ovl3, 0x4

dlabel D_8006C06C_ovl3
    /* 8006C06C */ .space 0x04

nonmatching D_8006C070_ovl3, 0x4

dlabel D_8006C070_ovl3
    /* 8006C070 */ .space 0x04

nonmatching D_8006C074_ovl3, 0x4

dlabel D_8006C074_ovl3
    /* 8006C074 */ .space 0x04

nonmatching D_8006C078_ovl3, 0x4

dlabel D_8006C078_ovl3
    /* 8006C078 */ .space 0x04

nonmatching D_8006C07C_ovl3, 0x4

dlabel D_8006C07C_ovl3
    /* 8006C07C */ .space 0x04

nonmatching D_8006C080_ovl3, 0x4

dlabel D_8006C080_ovl3
    /* 8006C080 */ .space 0x04

nonmatching D_8006C084_ovl3, 0xC

dlabel D_8006C084_ovl3
    /* 8006C084 */ .space 0x0C

nonmatching D_8006C090_ovl3, 0xC

dlabel D_8006C090_ovl3
    /* 8006C090 */ .space 0x0C

nonmatching D_8006C09C_ovl3, 0x4

dlabel D_8006C09C_ovl3
    /* 8006C09C */ .space 0x04

nonmatching D_8006C0A0_ovl3, 0x4

dlabel D_8006C0A0_ovl3
    /* 8006C0A0 */ .space 0x04

nonmatching D_8006C0A4_ovl3, 0x4

dlabel D_8006C0A4_ovl3
    /* 8006C0A4 */ .space 0x04

nonmatching D_8006C0A8_ovl3, 0x14

dlabel D_8006C0A8_ovl3
    /* 8006C0A8 */ .space 0x14

nonmatching D_8006C0BC_ovl3, 0x4

dlabel D_8006C0BC_ovl3
    /* 8006C0BC */ .space 0x04

nonmatching D_8006C0C0_ovl3, 0x4

dlabel D_8006C0C0_ovl3
    /* 8006C0C0 */ .space 0x04

nonmatching D_8006C0C4_ovl3, 0xC

dlabel D_8006C0C4_ovl3
    /* 8006C0C4 */ .space 0x0C

nonmatching D_8006C0D0_ovl3, 0x4

dlabel D_8006C0D0_ovl3
    /* 8006C0D0 */ .space 0x04

nonmatching D_8006C0D4_ovl3, 0x4

dlabel D_8006C0D4_ovl3
    /* 8006C0D4 */ .space 0x04

nonmatching D_8006C0D8_ovl3, 0x4

dlabel D_8006C0D8_ovl3
    /* 8006C0D8 */ .space 0x04

nonmatching D_8006C0DC_ovl3, 0x4

dlabel D_8006C0DC_ovl3
    /* 8006C0DC */ .space 0x04

nonmatching D_8006C0E0_ovl3, 0x4

dlabel D_8006C0E0_ovl3
    /* 8006C0E0 */ .space 0x04

nonmatching D_8006C0E4_ovl3, 0x4

dlabel D_8006C0E4_ovl3
    /* 8006C0E4 */ .space 0x04

nonmatching D_8006C0E8_ovl3, 0x8

dlabel D_8006C0E8_ovl3
    /* 8006C0E8 */ .space 0x08

nonmatching D_8006C0F0_ovl3, 0x14

dlabel D_8006C0F0_ovl3
    /* 8006C0F0 */ .space 0x14

nonmatching D_8006C104_ovl3, 0x2

dlabel D_8006C104_ovl3
    /* 8006C104 */ .space 0x02

nonmatching D_8006C106_ovl3, 0x2

dlabel D_8006C106_ovl3
    /* 8006C106 */ .space 0x02

nonmatching D_8006C108_ovl3, 0x4

dlabel D_8006C108_ovl3
    /* 8006C108 */ .space 0x04

nonmatching D_8006C10C_ovl3, 0x4

dlabel D_8006C10C_ovl3
    /* 8006C10C */ .space 0x04

nonmatching D_8006C110_ovl3, 0x10

dlabel D_8006C110_ovl3
    /* 8006C110 */ .space 0x10

nonmatching D_8006C120_ovl3, 0x1

dlabel D_8006C120_ovl3
    /* 8006C120 */ .space 0x01

nonmatching D_8006C121_ovl3, 0x1

dlabel D_8006C121_ovl3
    /* 8006C121 */ .space 0x01

nonmatching D_8006C122_ovl3, 0x1

dlabel D_8006C122_ovl3
    /* 8006C122 */ .space 0x01

nonmatching D_8006C123_ovl3, 0x1

dlabel D_8006C123_ovl3
    /* 8006C123 */ .space 0x01

nonmatching D_8006C124_ovl3, 0x1

dlabel D_8006C124_ovl3
    /* 8006C124 */ .space 0x01

nonmatching D_8006C125_ovl3, 0x1

dlabel D_8006C125_ovl3
    /* 8006C125 */ .space 0x01

nonmatching D_8006C126_ovl3, 0x4

dlabel D_8006C126_ovl3
    /* 8006C126 */ .space 0x04

nonmatching D_8006C12A_ovl3, 0x6

dlabel D_8006C12A_ovl3
    /* 8006C12A */ .space 0x06

nonmatching D_8006C130_ovl3, 0x4

dlabel D_8006C130_ovl3
    /* 8006C130 */ .space 0x04

nonmatching D_8006C134_ovl3, 0xC

dlabel D_8006C134_ovl3
    /* 8006C134 */ .space 0x0C

nonmatching D_8006C140_ovl3, 0x4

dlabel D_8006C140_ovl3
    /* 8006C140 */ .space 0x04

nonmatching D_8006C144_ovl3, 0x4

dlabel D_8006C144_ovl3
    /* 8006C144 */ .space 0x04

nonmatching D_8006C148_ovl3, 0x4

dlabel D_8006C148_ovl3
    /* 8006C148 */ .space 0x04

nonmatching D_8006C14C_ovl3, 0x4

dlabel D_8006C14C_ovl3
    /* 8006C14C */ .space 0x04

nonmatching D_8006C150_ovl3, 0x4

dlabel D_8006C150_ovl3
    /* 8006C150 */ .space 0x04

nonmatching D_8006C154_ovl3, 0x4

dlabel D_8006C154_ovl3
    /* 8006C154 */ .space 0x04

nonmatching D_8006C158_ovl3, 0x8

dlabel D_8006C158_ovl3
    /* 8006C158 */ .space 0x08

nonmatching D_8006C160_ovl3, 0xC

dlabel D_8006C160_ovl3
    /* 8006C160 */ .space 0x0C

nonmatching D_8006C16C_ovl3, 0x10

dlabel D_8006C16C_ovl3
    /* 8006C16C */ .space 0x10

nonmatching D_8006C17C_ovl3, 0x4

dlabel D_8006C17C_ovl3
    /* 8006C17C */ .space 0x04

nonmatching D_8006C180_ovl3, 0x10

dlabel D_8006C180_ovl3
    /* 8006C180 */ .space 0x10

nonmatching D_8006C190_ovl3, 0x10

dlabel D_8006C190_ovl3
    /* 8006C190 */ .space 0x10

nonmatching D_8006C1A0_ovl3, 0x4

dlabel D_8006C1A0_ovl3
    /* 8006C1A0 */ .space 0x04

nonmatching D_8006C1A4_ovl3, 0xC

dlabel D_8006C1A4_ovl3
    /* 8006C1A4 */ .space 0x0C

nonmatching D_8006C1B0_ovl3, 0x4

dlabel D_8006C1B0_ovl3
    /* 8006C1B0 */ .space 0x04

nonmatching D_8006C1B4_ovl3, 0x4

dlabel D_8006C1B4_ovl3
    /* 8006C1B4 */ .space 0x04

nonmatching D_8006C1B8_ovl3, 0x4

dlabel D_8006C1B8_ovl3
    /* 8006C1B8 */ .space 0x04

nonmatching D_8006C1BC_ovl3, 0x4

dlabel D_8006C1BC_ovl3
    /* 8006C1BC */ .space 0x04

nonmatching D_8006C1C0_ovl3, 0x4

dlabel D_8006C1C0_ovl3
    /* 8006C1C0 */ .space 0x04

nonmatching D_8006C1C4_ovl3, 0x4

dlabel D_8006C1C4_ovl3
    /* 8006C1C4 */ .space 0x04

nonmatching D_8006C1C8_ovl3, 0x4

dlabel D_8006C1C8_ovl3
    /* 8006C1C8 */ .space 0x04

nonmatching D_8006C1CC_ovl3, 0x4

dlabel D_8006C1CC_ovl3
    /* 8006C1CC */ .space 0x04

nonmatching D_8006C1D0_ovl3, 0x4

dlabel D_8006C1D0_ovl3
    /* 8006C1D0 */ .space 0x04

nonmatching D_8006C1D4_ovl3, 0xC

dlabel D_8006C1D4_ovl3
    /* 8006C1D4 */ .space 0x0C

nonmatching D_8006C1E0_ovl3, 0x4

dlabel D_8006C1E0_ovl3
    /* 8006C1E0 */ .space 0x04

nonmatching D_8006C1E4_ovl3, 0x4

dlabel D_8006C1E4_ovl3
    /* 8006C1E4 */ .space 0x04

nonmatching D_8006C1E8_ovl3, 0x2

dlabel D_8006C1E8_ovl3
    /* 8006C1E8 */ .space 0x02

nonmatching D_8006C1EA_ovl3, 0x2

dlabel D_8006C1EA_ovl3
    /* 8006C1EA */ .space 0x02

nonmatching D_8006C1EC_ovl3, 0x4

dlabel D_8006C1EC_ovl3
    /* 8006C1EC */ .space 0x04

nonmatching D_8006C1F0_ovl3, 0x4

dlabel D_8006C1F0_ovl3
    /* 8006C1F0 */ .space 0x04

nonmatching D_8006C1F4_ovl3, 0x4

dlabel D_8006C1F4_ovl3
    /* 8006C1F4 */ .space 0x04

nonmatching D_8006C1F8_ovl3, 0x4

dlabel D_8006C1F8_ovl3
    /* 8006C1F8 */ .space 0x04

nonmatching D_8006C1FC_ovl3, 0x4

dlabel D_8006C1FC_ovl3
    /* 8006C1FC */ .space 0x04

nonmatching D_8006C200_ovl3, 0x10

dlabel D_8006C200_ovl3
    /* 8006C200 */ .space 0x10

nonmatching D_8006C210_ovl3, 0x4

dlabel D_8006C210_ovl3
    /* 8006C210 */ .space 0x04

nonmatching D_8006C214_ovl3, 0x4

dlabel D_8006C214_ovl3
    /* 8006C214 */ .space 0x04

nonmatching D_8006C218_ovl3, 0x8

dlabel D_8006C218_ovl3
    /* 8006C218 */ .space 0x08

nonmatching D_8006C220_ovl3, 0xC

dlabel D_8006C220_ovl3
    /* 8006C220 */ .space 0x0C

nonmatching D_8006C22C_ovl3, 0x14

dlabel D_8006C22C_ovl3
    /* 8006C22C */ .space 0x14

nonmatching D_8006C240_ovl3, 0x8

dlabel D_8006C240_ovl3
    /* 8006C240 */ .space 0x08

nonmatching D_8006C248_ovl3, 0x4

dlabel D_8006C248_ovl3
    /* 8006C248 */ .space 0x04

nonmatching D_8006C24C_ovl3, 0x10

dlabel D_8006C24C_ovl3
    /* 8006C24C */ .space 0x10

nonmatching D_8006C25C_ovl3, 0x4

dlabel D_8006C25C_ovl3
    /* 8006C25C */ .space 0x04

nonmatching D_8006C260_ovl3, 0x4

dlabel D_8006C260_ovl3
    /* 8006C260 */ .space 0x04

nonmatching D_8006C264_ovl3, 0x4

dlabel D_8006C264_ovl3
    /* 8006C264 */ .space 0x04

nonmatching D_8006C268_ovl3, 0x4

dlabel D_8006C268_ovl3
    /* 8006C268 */ .space 0x04

nonmatching D_8006C26C_ovl3, 0x4

dlabel D_8006C26C_ovl3
    /* 8006C26C */ .space 0x04

nonmatching D_8006C270_ovl3, 0x2

dlabel D_8006C270_ovl3
    /* 8006C270 */ .space 0x02

nonmatching D_8006C272_ovl3, 0x2

dlabel D_8006C272_ovl3
    /* 8006C272 */ .space 0x02

nonmatching D_8006C274_ovl3, 0x4

dlabel D_8006C274_ovl3
    /* 8006C274 */ .space 0x04

nonmatching D_8006C278_ovl3, 0x2

dlabel D_8006C278_ovl3
    /* 8006C278 */ .space 0x02

nonmatching D_8006C27A_ovl3, 0x2

dlabel D_8006C27A_ovl3
    /* 8006C27A */ .space 0x02

nonmatching D_8006C27C_ovl3, 0x4

dlabel D_8006C27C_ovl3
    /* 8006C27C */ .space 0x04

nonmatching D_8006C280_ovl3, 0x4

dlabel D_8006C280_ovl3
    /* 8006C280 */ .space 0x04

nonmatching D_8006C284_ovl3, 0x4

dlabel D_8006C284_ovl3
    /* 8006C284 */ .space 0x04

nonmatching D_8006C288_ovl3, 0x8

dlabel D_8006C288_ovl3
    /* 8006C288 */ .space 0x08

nonmatching D_8006C290_ovl3, 0x4

dlabel D_8006C290_ovl3
    /* 8006C290 */ .space 0x04

nonmatching D_8006C294_ovl3, 0x4

dlabel D_8006C294_ovl3
    /* 8006C294 */ .space 0x04

nonmatching D_8006C298_ovl3, 0x4

dlabel D_8006C298_ovl3
    /* 8006C298 */ .space 0x04

nonmatching D_8006C29C_ovl3, 0x8

dlabel D_8006C29C_ovl3
    /* 8006C29C */ .space 0x08

nonmatching D_8006C2A4_ovl3, 0x4

dlabel D_8006C2A4_ovl3
    /* 8006C2A4 */ .space 0x04

nonmatching D_8006C2A8_ovl3, 0xC

dlabel D_8006C2A8_ovl3
    /* 8006C2A8 */ .space 0x0C

nonmatching D_8006C2B4_ovl3, 0xC

dlabel D_8006C2B4_ovl3
    /* 8006C2B4 */ .space 0x0C

nonmatching D_8006C2C0_ovl3, 0xC

dlabel D_8006C2C0_ovl3
    /* 8006C2C0 */ .space 0x0C

nonmatching D_8006C2CC_ovl3, 0x1

dlabel D_8006C2CC_ovl3
    /* 8006C2CC */ .space 0x01

nonmatching D_8006C2CD_ovl3, 0x1

dlabel D_8006C2CD_ovl3
    /* 8006C2CD */ .space 0x01

nonmatching D_8006C2CE_ovl3, 0x6

dlabel D_8006C2CE_ovl3
    /* 8006C2CE */ .space 0x06

nonmatching D_8006C2D4_ovl3, 0xC

dlabel D_8006C2D4_ovl3
    /* 8006C2D4 */ .space 0x0C

nonmatching D_8006C2E0_ovl3, 0x10

dlabel D_8006C2E0_ovl3
    /* 8006C2E0 */ .space 0x10

nonmatching D_8006C2F0_ovl3, 0x4

dlabel D_8006C2F0_ovl3
    /* 8006C2F0 */ .space 0x04

nonmatching D_8006C2F4_ovl3, 0x4

dlabel D_8006C2F4_ovl3
    /* 8006C2F4 */ .space 0x04

nonmatching D_8006C2F8_ovl3, 0x4

dlabel D_8006C2F8_ovl3
    /* 8006C2F8 */ .space 0x04

nonmatching D_8006C2FC_ovl3, 0x4

dlabel D_8006C2FC_ovl3
    /* 8006C2FC */ .space 0x04

nonmatching D_8006C300_ovl3, 0x4

dlabel D_8006C300_ovl3
    /* 8006C300 */ .space 0x04

nonmatching D_8006C304_ovl3, 0x4

dlabel D_8006C304_ovl3
    /* 8006C304 */ .space 0x04

nonmatching D_8006C308_ovl3, 0x28

dlabel D_8006C308_ovl3
    /* 8006C308 */ .space 0x28

nonmatching D_8006C330_ovl3, 0x8

dlabel D_8006C330_ovl3
    /* 8006C330 */ .space 0x08

nonmatching D_8006C338_ovl3, 0x4

dlabel D_8006C338_ovl3
    /* 8006C338 */ .space 0x04

nonmatching D_8006C33C_ovl3, 0x4

dlabel D_8006C33C_ovl3
    /* 8006C33C */ .space 0x04

nonmatching D_8006C340_ovl3, 0x10

dlabel D_8006C340_ovl3
    /* 8006C340 */ .space 0x10

nonmatching D_8006C350_ovl3, 0x4

dlabel D_8006C350_ovl3
    /* 8006C350 */ .space 0x04

nonmatching D_8006C354_ovl3, 0x4

dlabel D_8006C354_ovl3
    /* 8006C354 */ .space 0x04

nonmatching D_8006C358_ovl3, 0x4

dlabel D_8006C358_ovl3
    /* 8006C358 */ .space 0x04

nonmatching D_8006C35C_ovl3, 0x14

dlabel D_8006C35C_ovl3
    /* 8006C35C */ .space 0x14

nonmatching D_8006C370_ovl3, 0x4

dlabel D_8006C370_ovl3
    /* 8006C370 */ .space 0x04

nonmatching D_8006C374_ovl3, 0x4

dlabel D_8006C374_ovl3
    /* 8006C374 */ .space 0x04

nonmatching D_8006C378_ovl3, 0x4

dlabel D_8006C378_ovl3
    /* 8006C378 */ .space 0x04

nonmatching D_8006C37C_ovl3, 0x4

dlabel D_8006C37C_ovl3
    /* 8006C37C */ .space 0x04

nonmatching D_8006C380_ovl3, 0x4

dlabel D_8006C380_ovl3
    /* 8006C380 */ .space 0x04

nonmatching D_8006C384_ovl3, 0x1

dlabel D_8006C384_ovl3
    /* 8006C384 */ .space 0x01

nonmatching D_8006C385_ovl3, 0x1

dlabel D_8006C385_ovl3
    /* 8006C385 */ .space 0x01

nonmatching D_8006C386_ovl3, 0x2

dlabel D_8006C386_ovl3
    /* 8006C386 */ .space 0x02

nonmatching D_8006C388_ovl3, 0x4

dlabel D_8006C388_ovl3
    /* 8006C388 */ .space 0x04

nonmatching D_8006C38C_ovl3, 0x4

dlabel D_8006C38C_ovl3
    /* 8006C38C */ .space 0x04

nonmatching D_8006C390_ovl3, 0x4

dlabel D_8006C390_ovl3
    /* 8006C390 */ .space 0x04

nonmatching D_8006C394_ovl3, 0x4

dlabel D_8006C394_ovl3
    /* 8006C394 */ .space 0x04

nonmatching D_8006C398_ovl3, 0x4

dlabel D_8006C398_ovl3
    /* 8006C398 */ .space 0x04

nonmatching D_8006C39C_ovl3, 0x4

dlabel D_8006C39C_ovl3
    /* 8006C39C */ .space 0x04

nonmatching D_8006C3A0_ovl3, 0x4

dlabel D_8006C3A0_ovl3
    /* 8006C3A0 */ .space 0x04

nonmatching D_8006C3A4_ovl3, 0x4

dlabel D_8006C3A4_ovl3
    /* 8006C3A4 */ .space 0x04

nonmatching D_8006C3A8_ovl3, 0x4

dlabel D_8006C3A8_ovl3
    /* 8006C3A8 */ .space 0x04

nonmatching D_8006C3AC_ovl3, 0x4

dlabel D_8006C3AC_ovl3
    /* 8006C3AC */ .space 0x04

nonmatching D_8006C3B0_ovl3, 0x4

dlabel D_8006C3B0_ovl3
    /* 8006C3B0 */ .space 0x04

nonmatching D_8006C3B4_ovl3, 0x4

dlabel D_8006C3B4_ovl3
    /* 8006C3B4 */ .space 0x04

nonmatching D_8006C3B8_ovl3, 0x4

dlabel D_8006C3B8_ovl3
    /* 8006C3B8 */ .space 0x04

nonmatching D_8006C3BC_ovl3, 0x4

dlabel D_8006C3BC_ovl3
    /* 8006C3BC */ .space 0x04

nonmatching D_8006C3C0_ovl3, 0x4

dlabel D_8006C3C0_ovl3
    /* 8006C3C0 */ .space 0x04

nonmatching D_8006C3C4_ovl3, 0x4

dlabel D_8006C3C4_ovl3
    /* 8006C3C4 */ .space 0x04

nonmatching D_8006C3C8_ovl3, 0x4

dlabel D_8006C3C8_ovl3
    /* 8006C3C8 */ .space 0x04

nonmatching D_8006C3CC_ovl3, 0x8

dlabel D_8006C3CC_ovl3
    /* 8006C3CC */ .space 0x08

nonmatching D_8006C3D4_ovl3, 0x4

dlabel D_8006C3D4_ovl3
    /* 8006C3D4 */ .space 0x04

nonmatching D_8006C3D8_ovl3, 0x4

dlabel D_8006C3D8_ovl3
    /* 8006C3D8 */ .space 0x04

nonmatching D_8006C3DC_ovl3, 0x4

dlabel D_8006C3DC_ovl3
    /* 8006C3DC */ .space 0x04

nonmatching D_8006C3E0_ovl3, 0x4

dlabel D_8006C3E0_ovl3
    /* 8006C3E0 */ .space 0x04

nonmatching D_8006C3E4_ovl3, 0x4

dlabel D_8006C3E4_ovl3
    /* 8006C3E4 */ .space 0x04

nonmatching D_8006C3E8_ovl3, 0x4

dlabel D_8006C3E8_ovl3
    /* 8006C3E8 */ .space 0x04

nonmatching D_8006C3EC_ovl3, 0x4

dlabel D_8006C3EC_ovl3
    /* 8006C3EC */ .space 0x04

nonmatching D_8006C3F0_ovl3, 0x4

dlabel D_8006C3F0_ovl3
    /* 8006C3F0 */ .space 0x04

nonmatching D_8006C3F4_ovl3, 0x164

dlabel D_8006C3F4_ovl3
    /* 8006C3F4 */ .space 0x164

nonmatching D_8006C558_ovl3, 0x2

dlabel D_8006C558_ovl3
    /* 8006C558 */ .space 0x02

nonmatching D_8006C55A_ovl3, 0x2

dlabel D_8006C55A_ovl3
    /* 8006C55A */ .space 0x02

nonmatching D_8006C55C_ovl3, 0x4

dlabel D_8006C55C_ovl3
    /* 8006C55C */ .space 0x04

nonmatching D_8006C560_ovl3, 0x4

dlabel D_8006C560_ovl3
    /* 8006C560 */ .space 0x04

nonmatching D_8006C564_ovl3, 0x4

dlabel D_8006C564_ovl3
    /* 8006C564 */ .space 0x04

nonmatching D_8006C568_ovl3, 0x4

dlabel D_8006C568_ovl3
    /* 8006C568 */ .space 0x04

nonmatching D_8006C56C_ovl3, 0x4

dlabel D_8006C56C_ovl3
    /* 8006C56C */ .space 0x04

nonmatching D_8006C570_ovl3, 0x4

dlabel D_8006C570_ovl3
    /* 8006C570 */ .space 0x04

nonmatching D_8006C574_ovl3, 0x4

dlabel D_8006C574_ovl3
    /* 8006C574 */ .space 0x04

nonmatching D_8006C578_ovl3, 0x4

dlabel D_8006C578_ovl3
    /* 8006C578 */ .space 0x04

nonmatching D_8006C57C_ovl3, 0x4

dlabel D_8006C57C_ovl3
    /* 8006C57C */ .space 0x04

nonmatching D_8006C580_ovl3, 0x1

dlabel D_8006C580_ovl3
    /* 8006C580 */ .space 0x01

nonmatching D_8006C581_ovl3, 0x1

dlabel D_8006C581_ovl3
    /* 8006C581 */ .space 0x01

nonmatching D_8006C582_ovl3, 0x1

dlabel D_8006C582_ovl3
    /* 8006C582 */ .space 0x01

nonmatching D_8006C583_ovl3, 0x1

dlabel D_8006C583_ovl3
    /* 8006C583 */ .space 0x01

nonmatching D_8006C584_ovl3, 0x1

dlabel D_8006C584_ovl3
    /* 8006C584 */ .space 0x01

nonmatching D_8006C585_ovl3, 0x3

dlabel D_8006C585_ovl3
    /* 8006C585 */ .space 0x03

nonmatching D_8006C588_ovl3, 0x4

dlabel D_8006C588_ovl3
    /* 8006C588 */ .space 0x04

nonmatching D_8006C58C_ovl3, 0x4

dlabel D_8006C58C_ovl3
    /* 8006C58C */ .space 0x04

nonmatching D_8006C590_ovl3, 0x4

dlabel D_8006C590_ovl3
    /* 8006C590 */ .space 0x04

nonmatching D_8006C594_ovl3, 0x4

dlabel D_8006C594_ovl3
    /* 8006C594 */ .space 0x04

nonmatching D_8006C598_ovl3, 0x4

dlabel D_8006C598_ovl3
    /* 8006C598 */ .space 0x04

nonmatching D_8006C59C_ovl3, 0x4

dlabel D_8006C59C_ovl3
    /* 8006C59C */ .space 0x04
