.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80025FB0_ovl6, 0x8

glabel func_80025FB0_ovl6
    /* 14FD10 80025FB0 03E00008 */  jr         $ra
    /* 14FD14 80025FB4 00000000 */   nop
endlabel func_80025FB0_ovl6
    /* 14FD18 80025FB8 00000000 */  nop
    /* 14FD1C 80025FBC 00000000 */  nop
