.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.39.3 */

.align 2
nonmatching D_8005AA40_ovl5

dlabel D_8005AA40_ovl5
    /* 14C840 8005AA40 */ .asciz "lhand"
    /* 6C68616E64000000 */
.align 2
enddlabel D_8005AA40_ovl5

.align 2
nonmatching D_8005AA48_ovl5

dlabel D_8005AA48_ovl5
    /* 14C848 8005AA48 */ .asciz "rhand"
    /* 7268616E64000000 */
.align 2
enddlabel D_8005AA48_ovl5

.align 2
nonmatching D_8005AA50_ovl5

dlabel D_8005AA50_ovl5
    /* 14C850 8005AA50 */ .asciz "arm"
    /* 61726D00 */
.align 2
enddlabel D_8005AA50_ovl5
