.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.39.3 */

.align 2
nonmatching D_8005A5B0_ovl5

dlabel D_8005A5B0_ovl5
    /* 14C3B0 8005A5B0 */ .asciz "MODEL VIEW"
    /* 4D4F44454C20564945570000 */
.align 2
enddlabel D_8005A5B0_ovl5

.align 2
nonmatching D_8005A5BC_ovl5

dlabel D_8005A5BC_ovl5
    /* 14C3BC 8005A5BC */ .asciz "M11   CONT"
    /* 4D3131202020434F4E540000 */
.align 2
enddlabel D_8005A5BC_ovl5

.align 2
nonmatching D_8005A5C8_ovl5

dlabel D_8005A5C8_ovl5
    /* 14C3C8 8005A5C8 */ .asciz "M11   GAME"
    /* 4D313120202047414D450000 */
.align 2
enddlabel D_8005A5C8_ovl5

.align 2
nonmatching D_8005A5D4_ovl5

dlabel D_8005A5D4_ovl5
    /* 14C3D4 8005A5D4 */ .asciz "M11   TEST"
    /* 4D3131202020544553540000 */
.align 2
enddlabel D_8005A5D4_ovl5

.align 2
nonmatching D_8005A5E0_ovl5

dlabel D_8005A5E0_ovl5
    /* 14C3E0 8005A5E0 */ .asciz "M07   CONT"
    /* 4D3037202020434F4E540000 */
.align 2
enddlabel D_8005A5E0_ovl5

.align 2
nonmatching D_8005A5EC_ovl5

dlabel D_8005A5EC_ovl5
    /* 14C3EC 8005A5EC */ .asciz "M07   GAME"
    /* 4D303720202047414D450000 */
.align 2
enddlabel D_8005A5EC_ovl5

.align 2
nonmatching D_8005A5F8_ovl5

dlabel D_8005A5F8_ovl5
    /* 14C3F8 8005A5F8 */ .asciz "M07   TEST"
    /* 4D3037202020544553540000 */
.align 2
enddlabel D_8005A5F8_ovl5

.align 2
nonmatching D_8005A604_ovl5

dlabel D_8005A604_ovl5
    /* 14C404 8005A604 */ .asciz "M04   CONT"
    /* 4D3034202020434F4E540000 */
.align 2
enddlabel D_8005A604_ovl5

.align 2
nonmatching D_8005A610_ovl5

dlabel D_8005A610_ovl5
    /* 14C410 8005A610 */ .asciz "M04   GAME"
    /* 4D303420202047414D450000 */
.align 2
enddlabel D_8005A610_ovl5

.align 2
nonmatching D_8005A61C_ovl5

dlabel D_8005A61C_ovl5
    /* 14C41C 8005A61C */ .asciz "M04   TEST"
    /* 4D3034202020544553540000 */
.align 2
enddlabel D_8005A61C_ovl5

.align 2
nonmatching D_8005A628_ovl5

dlabel D_8005A628_ovl5
    /* 14C428 8005A628 */ .asciz "HAS TEST"
    /* 484153205445535400000000 */
.align 2
.align 2
    /* 14C434 8005A634 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_8005A628_ovl5

.align 3
nonmatching jtbl_8005A638_ovl5

dlabel jtbl_8005A638_ovl5
    /* 14C438 8005A638 80025C30 */ .word .L80025C30_ovl5
    /* 14C43C 8005A63C 80025C68 */ .word .L80025C68_ovl5
    /* 14C440 8005A640 80025CB4 */ .word .L80025CB4_ovl5
    /* 14C444 8005A644 80025D20 */ .word .L80025D20_ovl5
    /* 14C448 8005A648 80025D44 */ .word .L80025D44_ovl5
    /* 14C44C 8005A64C 00000000 */ .word 0x00000000
enddlabel jtbl_8005A638_ovl5
