.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.39.3 */

nonmatching D_8005A650_ovl5

dlabel D_8005A650_ovl5
    /* 14C450 8005A650 40400000 */ .float 3
enddlabel D_8005A650_ovl5

nonmatching D_8005A654_ovl5

dlabel D_8005A654_ovl5
    /* 14C454 8005A654 00000000 */ .float 0
    /* 14C458 8005A658 40000000 */ .float 2
    /* 14C45C 8005A65C 3F800000 */ .float 1
    /* 14C460 8005A660 3F800000 */ .float 1
    /* 14C464 8005A664 40200000 */ .float 2.5
    /* 14C468 8005A668 40400000 */ .float 3
    /* 14C46C 8005A66C 00000000 */ .float 0
    /* 14C470 8005A670 40000000 */ .float 2
    /* 14C474 8005A674 3F800000 */ .float 1
    /* 14C478 8005A678 3F800000 */ .float 1
    /* 14C47C 8005A67C 40000000 */ .float 2
    /* 14C480 8005A680 40400000 */ .float 3
    /* 14C484 8005A684 00000000 */ .float 0
    /* 14C488 8005A688 40000000 */ .float 2
    /* 14C48C 8005A68C 3F4CCCCD */ .float 0.8000000119
    /* 14C490 8005A690 3F800000 */ .float 1
    /* 14C494 8005A694 3FC00000 */ .float 1.5
enddlabel D_8005A654_ovl5

.align 2
nonmatching D_8005A698_ovl5

dlabel D_8005A698_ovl5
    /* 14C498 8005A698 */ .asciz "lhand"
    /* 6C68616E64000000 */
.align 2
enddlabel D_8005A698_ovl5

.align 2
nonmatching D_8005A6A0_ovl5

dlabel D_8005A6A0_ovl5
    /* 14C4A0 8005A6A0 */ .asciz "rhand"
    /* 7268616E64000000 */
.align 2
enddlabel D_8005A6A0_ovl5

.align 2
nonmatching D_8005A6A8_ovl5

dlabel D_8005A6A8_ovl5
    /* 14C4A8 8005A6A8 */ .asciz "arm"
    /* 61726D00 */
.align 2
.align 2
    /* 14C4AC 8005A6AC */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_8005A6A8_ovl5
