.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.39.3 */

nonmatching D_8005A6B0_ovl5

dlabel D_8005A6B0_ovl5
    /* 14C4B0 8005A6B0 8014A064 */ .word D_8014A064
    /* 14C4B4 8005A6B4 8014A068 */ .word D_8014A068
    /* 14C4B8 8005A6B8 8014A06C */ .word D_8014A06C
    /* 14C4BC 8005A6BC 8014A088 */ .word D_8014A088
    /* 14C4C0 8005A6C0 8014A07C */ .word D_8014A07C
    /* 14C4C4 8005A6C4 8014A080 */ .word D_8014A080
    /* 14C4C8 8005A6C8 8014A084 */ .word D_8014A084
    /* 14C4CC 8005A6CC 00000000 */ .word 0x00000000
enddlabel D_8005A6B0_ovl5
