.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.39.3 */

nonmatching D_80029AF0_ovl4, 0x4

dlabel D_80029AF0_ovl4
    /* 80029AF0 */ .space 0x04

nonmatching D_80029AF4_ovl4, 0xC

dlabel D_80029AF4_ovl4
    /* 80029AF4 */ .space 0x0C

nonmatching D_80029B00_ovl4, 0x8

dlabel D_80029B00_ovl4
    /* 80029B00 */ .space 0x08

nonmatching D_80029B08_ovl4, 0xC6

dlabel D_80029B08_ovl4
    /* 80029B08 */ .space 0xC6

nonmatching D_80029BCE_ovl4, 0x2

dlabel D_80029BCE_ovl4
    /* 80029BCE */ .space 0x02

nonmatching D_80029BD0_ovl4, 0x4

dlabel D_80029BD0_ovl4
    /* 80029BD0 */ .space 0x04

nonmatching D_80029BD4_ovl4, 0x4

dlabel D_80029BD4_ovl4
    /* 80029BD4 */ .space 0x04

nonmatching D_80029BD8_ovl4, 0x4

dlabel D_80029BD8_ovl4
    /* 80029BD8 */ .space 0x04

nonmatching D_80029BDC_ovl4, 0x4

dlabel D_80029BDC_ovl4
    /* 80029BDC */ .space 0x04

nonmatching D_80029BE0_ovl4, 0x40

dlabel D_80029BE0_ovl4
    /* 80029BE0 */ .space 0x40

nonmatching D_80029C20_ovl4, 0x4

dlabel D_80029C20_ovl4
    /* 80029C20 */ .space 0x04

nonmatching D_80029C24_ovl4, 0x4

dlabel D_80029C24_ovl4
    /* 80029C24 */ .space 0x04

nonmatching D_80029C28_ovl4, 0x4

dlabel D_80029C28_ovl4
    /* 80029C28 */ .space 0x04

nonmatching D_80029C2C_ovl4, 0x4

dlabel D_80029C2C_ovl4
    /* 80029C2C */ .space 0x04

nonmatching D_80029C30_ovl4, 0xA00

dlabel D_80029C30_ovl4
    /* 80029C30 */ .space 0xA00

nonmatching D_8002A630_ovl4, 0x4

dlabel D_8002A630_ovl4
    /* 8002A630 */ .space 0x04

nonmatching D_8002A634_ovl4, 0x4

dlabel D_8002A634_ovl4
    /* 8002A634 */ .space 0x04

nonmatching D_8002A638_ovl4, 0x40

dlabel D_8002A638_ovl4
    /* 8002A638 */ .space 0x40

nonmatching D_8002A678_ovl4, 0x4

dlabel D_8002A678_ovl4
    /* 8002A678 */ .space 0x04

nonmatching D_8002A67C_ovl4, 0x4

dlabel D_8002A67C_ovl4
    /* 8002A67C */ .space 0x04

nonmatching D_8002A680_ovl4, 0x4

dlabel D_8002A680_ovl4
    /* 8002A680 */ .space 0x04

nonmatching D_8002A684_ovl4, 0x4

dlabel D_8002A684_ovl4
    /* 8002A684 */ .space 0x04

nonmatching D_8002A688_ovl4, 0x48

dlabel D_8002A688_ovl4
    /* 8002A688 */ .space 0x48

nonmatching D_8002A6D0_ovl4, 0x780

dlabel D_8002A6D0_ovl4
    /* 8002A6D0 */ .space 0x780

nonmatching D_8002AE50_ovl4, 0x40

dlabel D_8002AE50_ovl4
    /* 8002AE50 */ .space 0x40

nonmatching D_8002AE90_ovl4, 0x40

dlabel D_8002AE90_ovl4
    /* 8002AE90 */ .space 0x40

nonmatching D_8002AED0_ovl4, 0x8

dlabel D_8002AED0_ovl4
    /* 8002AED0 */ .space 0x08

nonmatching D_8002AED8_ovl4, 0x40

dlabel D_8002AED8_ovl4
    /* 8002AED8 */ .space 0x40

nonmatching D_8002AF18_ovl4, 0x4

dlabel D_8002AF18_ovl4
    /* 8002AF18 */ .space 0x04

nonmatching D_8002AF1C_ovl4, 0x4

dlabel D_8002AF1C_ovl4
    /* 8002AF1C */ .space 0x04

nonmatching D_8002AF20_ovl4, 0x4

dlabel D_8002AF20_ovl4
    /* 8002AF20 */ .space 0x04

nonmatching D_8002AF24_ovl4, 0x4

dlabel D_8002AF24_ovl4
    /* 8002AF24 */ .space 0x04

nonmatching D_8002AF28_ovl4, 0x2

dlabel D_8002AF28_ovl4
    /* 8002AF28 */ .space 0x02

nonmatching D_8002AF2A_ovl4, 0x2

dlabel D_8002AF2A_ovl4
    /* 8002AF2A */ .space 0x02

nonmatching D_8002AF2C_ovl4, 0xC

dlabel D_8002AF2C_ovl4
    /* 8002AF2C */ .space 0x0C

nonmatching D_8002AF38_ovl4, 0x76

dlabel D_8002AF38_ovl4
    /* 8002AF38 */ .space 0x76

nonmatching D_8002AFAE_ovl4, 0x2

dlabel D_8002AFAE_ovl4
    /* 8002AFAE */ .space 0x02

nonmatching D_8002AFB0_ovl4, 0x4

dlabel D_8002AFB0_ovl4
    /* 8002AFB0 */ .space 0x04

nonmatching D_8002AFB4_ovl4, 0x4

dlabel D_8002AFB4_ovl4
    /* 8002AFB4 */ .space 0x04

nonmatching D_8002AFB8_ovl4, 0x4

dlabel D_8002AFB8_ovl4
    /* 8002AFB8 */ .space 0x04

nonmatching D_8002AFBC_ovl4, 0x2

dlabel D_8002AFBC_ovl4
    /* 8002AFBC */ .space 0x02

nonmatching D_8002AFBE_ovl4, 0x2

dlabel D_8002AFBE_ovl4
    /* 8002AFBE */ .space 0x02

nonmatching D_8002AFC0_ovl4, 0x8

dlabel D_8002AFC0_ovl4
    /* 8002AFC0 */ .space 0x08

nonmatching D_8002AFC8_ovl4, 0x40

dlabel D_8002AFC8_ovl4
    /* 8002AFC8 */ .space 0x40

nonmatching D_8002B008_ovl4, 0x8

dlabel D_8002B008_ovl4
    /* 8002B008 */ .space 0x08

nonmatching D_8002B010_ovl4, 0x2

dlabel D_8002B010_ovl4
    /* 8002B010 */ .space 0x02

nonmatching D_8002B012_ovl4, 0xF6

dlabel D_8002B012_ovl4
    /* 8002B012 */ .space 0xF6

nonmatching D_8002B108_ovl4, 0x4

dlabel D_8002B108_ovl4
    /* 8002B108 */ .space 0x04

nonmatching D_8002B10C_ovl4, 0x4

dlabel D_8002B10C_ovl4
    /* 8002B10C */ .space 0x04

nonmatching D_8002B110_ovl4, 0x4

dlabel D_8002B110_ovl4
    /* 8002B110 */ .space 0x04

nonmatching D_8002B114_ovl4, 0x4

dlabel D_8002B114_ovl4
    /* 8002B114 */ .space 0x04

nonmatching D_8002B118_ovl4, 0x4

dlabel D_8002B118_ovl4
    /* 8002B118 */ .space 0x04

nonmatching D_8002B11C_ovl4, 0x4

dlabel D_8002B11C_ovl4
    /* 8002B11C */ .space 0x04

nonmatching D_8002B120_ovl4, 0x4

dlabel D_8002B120_ovl4
    /* 8002B120 */ .space 0x04

nonmatching D_8002B124_ovl4, 0x4

dlabel D_8002B124_ovl4
    /* 8002B124 */ .space 0x04

nonmatching D_8002B128_ovl4, 0x8

dlabel D_8002B128_ovl4
    /* 8002B128 */ .space 0x08

nonmatching D_8002B130_ovl4, 0x9F8

dlabel D_8002B130_ovl4
    /* 8002B130 */ .space 0x9F8

nonmatching D_8002BB28_ovl4, 0x2

dlabel D_8002BB28_ovl4
    /* 8002BB28 */ .space 0x02

nonmatching D_8002BB2A_ovl4, 0x2

dlabel D_8002BB2A_ovl4
    /* 8002BB2A */ .space 0x02

nonmatching D_8002BB2C_ovl4, 0x4

dlabel D_8002BB2C_ovl4
    /* 8002BB2C */ .space 0x04

nonmatching D_8002BB30_ovl4, 0x40

dlabel D_8002BB30_ovl4
    /* 8002BB30 */ .space 0x40

nonmatching D_8002BB70_ovl4, 0x2

dlabel D_8002BB70_ovl4
    /* 8002BB70 */ .space 0x02

nonmatching D_8002BB72_ovl4, 0x2

dlabel D_8002BB72_ovl4
    /* 8002BB72 */ .space 0x02

nonmatching D_8002BB74_ovl4, 0x44

dlabel D_8002BB74_ovl4
    /* 8002BB74 */ .space 0x44

nonmatching D_8002BBB8_ovl4, 0x2

dlabel D_8002BBB8_ovl4
    /* 8002BBB8 */ .space 0x02

nonmatching D_8002BBBA_ovl4, 0x2

dlabel D_8002BBBA_ovl4
    /* 8002BBBA */ .space 0x02

nonmatching D_8002BBBC_ovl4, 0x514

dlabel D_8002BBBC_ovl4
    /* 8002BBBC */ .space 0x514

nonmatching D_8002C0D0_ovl4, 0x8

dlabel D_8002C0D0_ovl4
    /* 8002C0D0 */ .space 0x08

nonmatching D_8002C0D8_ovl4, 0x2

dlabel D_8002C0D8_ovl4
    /* 8002C0D8 */ .space 0x02

nonmatching D_8002C0DA_ovl4, 0x2

dlabel D_8002C0DA_ovl4
    /* 8002C0DA */ .space 0x02

nonmatching D_8002C0DC_ovl4, 0x4

dlabel D_8002C0DC_ovl4
    /* 8002C0DC */ .space 0x04

nonmatching D_8002C0E0_ovl4, 0x4

dlabel D_8002C0E0_ovl4
    /* 8002C0E0 */ .space 0x04

nonmatching D_8002C0E4_ovl4, 0x4

dlabel D_8002C0E4_ovl4
    /* 8002C0E4 */ .space 0x04

nonmatching D_8002C0E8_ovl4, 0x8

dlabel D_8002C0E8_ovl4
    /* 8002C0E8 */ .space 0x08

nonmatching D_8002C0F0_ovl4, 0x2

dlabel D_8002C0F0_ovl4
    /* 8002C0F0 */ .space 0x02

nonmatching D_8002C0F2_ovl4, 0x2

dlabel D_8002C0F2_ovl4
    /* 8002C0F2 */ .space 0x02

nonmatching D_8002C0F4_ovl4, 0x1CC

dlabel D_8002C0F4_ovl4
    /* 8002C0F4 */ .space 0x1CC
