.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.39.3 */

nonmatching D_8004B8E0_ovl6, 0x4

dlabel D_8004B8E0_ovl6
    /* 8004B8E0 */ .space 0x04

nonmatching D_8004B8E4_ovl6, 0xC

dlabel D_8004B8E4_ovl6
    /* 8004B8E4 */ .space 0x0C

nonmatching D_8004B8F0_ovl6, 0x14

dlabel D_8004B8F0_ovl6
    /* 8004B8F0 */ .space 0x14

nonmatching D_8004B904_ovl6, 0x2

dlabel D_8004B904_ovl6
    /* 8004B904 */ .space 0x02

nonmatching D_8004B906_ovl6, 0x2

dlabel D_8004B906_ovl6
    /* 8004B906 */ .space 0x02

nonmatching D_8004B908_ovl6, 0x2

dlabel D_8004B908_ovl6
    /* 8004B908 */ .space 0x02

nonmatching D_8004B90A_ovl6, 0x2

dlabel D_8004B90A_ovl6
    /* 8004B90A */ .space 0x02

nonmatching D_8004B90C_ovl6, 0x2

dlabel D_8004B90C_ovl6
    /* 8004B90C */ .space 0x02

nonmatching D_8004B90E_ovl6, 0x2

dlabel D_8004B90E_ovl6
    /* 8004B90E */ .space 0x02

nonmatching D_8004B910_ovl6, 0x4

dlabel D_8004B910_ovl6
    /* 8004B910 */ .space 0x04

nonmatching D_8004B914_ovl6, 0x4

dlabel D_8004B914_ovl6
    /* 8004B914 */ .space 0x04

nonmatching D_8004B918_ovl6, 0x8

dlabel D_8004B918_ovl6
    /* 8004B918 */ .space 0x08

nonmatching D_8004B920_ovl6, 0x4

dlabel D_8004B920_ovl6
    /* 8004B920 */ .space 0x04

nonmatching D_8004B924_ovl6, 0x3C

dlabel D_8004B924_ovl6
    /* 8004B924 */ .space 0x3C

nonmatching D_8004B960_ovl6, 0x18

dlabel D_8004B960_ovl6
    /* 8004B960 */ .space 0x18

nonmatching D_8004B978_ovl6, 0x4

dlabel D_8004B978_ovl6
    /* 8004B978 */ .space 0x04

nonmatching D_8004B97C_ovl6, 0x4

dlabel D_8004B97C_ovl6
    /* 8004B97C */ .space 0x04

nonmatching D_8004B980_ovl6, 0x80

dlabel D_8004B980_ovl6
    /* 8004B980 */ .space 0x80

nonmatching D_8004BA00_ovl6, 0x8

dlabel D_8004BA00_ovl6
    /* 8004BA00 */ .space 0x08

nonmatching D_8004BA08_ovl6, 0x4

dlabel D_8004BA08_ovl6
    /* 8004BA08 */ .space 0x04

nonmatching D_8004BA0C_ovl6, 0x4

dlabel D_8004BA0C_ovl6
    /* 8004BA0C */ .space 0x04

nonmatching D_8004BA10_ovl6, 0x38

dlabel D_8004BA10_ovl6
    /* 8004BA10 */ .space 0x38

nonmatching D_8004BA48_ovl6, 0x2

dlabel D_8004BA48_ovl6
    /* 8004BA48 */ .space 0x02

nonmatching D_8004BA4A_ovl6, 0x2

dlabel D_8004BA4A_ovl6
    /* 8004BA4A */ .space 0x02

nonmatching D_8004BA4C_ovl6, 0x4

dlabel D_8004BA4C_ovl6
    /* 8004BA4C */ .space 0x04

nonmatching D_8004BA50_ovl6, 0x28

dlabel D_8004BA50_ovl6
    /* 8004BA50 */ .space 0x28

nonmatching D_8004BA78_ovl6, 0x28

dlabel D_8004BA78_ovl6
    /* 8004BA78 */ .space 0x28

nonmatching D_8004BAA0_ovl6, 0x28

dlabel D_8004BAA0_ovl6
    /* 8004BAA0 */ .space 0x28

nonmatching D_8004BAC8_ovl6, 0x8

dlabel D_8004BAC8_ovl6
    /* 8004BAC8 */ .space 0x08

nonmatching D_8004BAD0_ovl6, 0xC8

dlabel D_8004BAD0_ovl6
    /* 8004BAD0 */ .space 0xC8

nonmatching D_8004BB98_ovl6, 0xC8

dlabel D_8004BB98_ovl6
    /* 8004BB98 */ .space 0xC8

nonmatching D_8004BC60_ovl6, 0x40

dlabel D_8004BC60_ovl6
    /* 8004BC60 */ .space 0x40

nonmatching D_8004BCA0_ovl6, 0x4

dlabel D_8004BCA0_ovl6
    /* 8004BCA0 */ .space 0x04

nonmatching D_8004BCA4_ovl6, 0x4

dlabel D_8004BCA4_ovl6
    /* 8004BCA4 */ .space 0x04

nonmatching D_8004BCA8_ovl6, 0x4

dlabel D_8004BCA8_ovl6
    /* 8004BCA8 */ .space 0x04

nonmatching D_8004BCAC_ovl6, 0x4

dlabel D_8004BCAC_ovl6
    /* 8004BCAC */ .space 0x04

nonmatching D_8004BCB0_ovl6, 0x4

dlabel D_8004BCB0_ovl6
    /* 8004BCB0 */ .space 0x04

nonmatching D_8004BCB4_ovl6, 0x2

dlabel D_8004BCB4_ovl6
    /* 8004BCB4 */ .space 0x02

nonmatching D_8004BCB6_ovl6, 0x2

dlabel D_8004BCB6_ovl6
    /* 8004BCB6 */ .space 0x02

nonmatching D_8004BCB8_ovl6, 0x8

dlabel D_8004BCB8_ovl6
    /* 8004BCB8 */ .space 0x08

nonmatching D_8004BCC0_ovl6, 0x100

dlabel D_8004BCC0_ovl6
    /* 8004BCC0 */ .space 0x100

nonmatching D_8004BDC0_ovl6, 0x10

dlabel D_8004BDC0_ovl6
    /* 8004BDC0 */ .space 0x10

nonmatching D_8004BDD0_ovl6, 0x18

dlabel D_8004BDD0_ovl6
    /* 8004BDD0 */ .space 0x18

nonmatching D_8004BDE8_ovl6, 0x18

dlabel D_8004BDE8_ovl6
    /* 8004BDE8 */ .space 0x18

nonmatching D_8004BE00_ovl6, 0x14

dlabel D_8004BE00_ovl6
    /* 8004BE00 */ .space 0x14

nonmatching D_8004BE14_ovl6, 0x2

dlabel D_8004BE14_ovl6
    /* 8004BE14 */ .space 0x02

nonmatching D_8004BE16_ovl6, 0x2

dlabel D_8004BE16_ovl6
    /* 8004BE16 */ .space 0x02

nonmatching D_8004BE18_ovl6, 0x2

dlabel D_8004BE18_ovl6
    /* 8004BE18 */ .space 0x02

nonmatching D_8004BE1A_ovl6, 0x6

dlabel D_8004BE1A_ovl6
    /* 8004BE1A */ .space 0x06

nonmatching D_8004BE20_ovl6, 0x10

dlabel D_8004BE20_ovl6
    /* 8004BE20 */ .space 0x10

nonmatching D_8004BE30_ovl6, 0x10

dlabel D_8004BE30_ovl6
    /* 8004BE30 */ .space 0x10

nonmatching D_8004BE40_ovl6, 0x10

dlabel D_8004BE40_ovl6
    /* 8004BE40 */ .space 0x10

nonmatching D_8004BE50_ovl6, 0x10

dlabel D_8004BE50_ovl6
    /* 8004BE50 */ .space 0x10

nonmatching D_8004BE60_ovl6, 0x4

dlabel D_8004BE60_ovl6
    /* 8004BE60 */ .space 0x04

nonmatching D_8004BE64_ovl6, 0x4

dlabel D_8004BE64_ovl6
    /* 8004BE64 */ .space 0x04

nonmatching D_8004BE68_ovl6, 0x2

dlabel D_8004BE68_ovl6
    /* 8004BE68 */ .space 0x02

nonmatching D_8004BE6A_ovl6, 0x2

dlabel D_8004BE6A_ovl6
    /* 8004BE6A */ .space 0x02

nonmatching D_8004BE6C_ovl6, 0x2

dlabel D_8004BE6C_ovl6
    /* 8004BE6C */ .space 0x02

nonmatching D_8004BE6E_ovl6, 0x2

dlabel D_8004BE6E_ovl6
    /* 8004BE6E */ .space 0x02

nonmatching D_8004BE70_ovl6, 0x4

dlabel D_8004BE70_ovl6
    /* 8004BE70 */ .space 0x04

nonmatching D_8004BE74_ovl6, 0xC

dlabel D_8004BE74_ovl6
    /* 8004BE74 */ .space 0x0C

nonmatching D_8004BE80_ovl6, 0x8

dlabel D_8004BE80_ovl6
    /* 8004BE80 */ .space 0x08

nonmatching D_8004BE88_ovl6, 0x17

dlabel D_8004BE88_ovl6
    /* 8004BE88 */ .space 0x17

nonmatching D_8004BE9F_ovl6, 0x1

dlabel D_8004BE9F_ovl6
    /* 8004BE9F */ .space 0x01

nonmatching D_8004BEA0_ovl6, 0x4

dlabel D_8004BEA0_ovl6
    /* 8004BEA0 */ .space 0x04

nonmatching D_8004BEA4_ovl6, 0x1

dlabel D_8004BEA4_ovl6
    /* 8004BEA4 */ .space 0x01

nonmatching D_8004BEA5_ovl6, 0x1

dlabel D_8004BEA5_ovl6
    /* 8004BEA5 */ .space 0x01

nonmatching D_8004BEA6_ovl6, 0x2

dlabel D_8004BEA6_ovl6
    /* 8004BEA6 */ .space 0x02

nonmatching D_8004BEA8_ovl6, 0x8

dlabel D_8004BEA8_ovl6
    /* 8004BEA8 */ .space 0x08

nonmatching D_8004BEB0_ovl6, 0x4

dlabel D_8004BEB0_ovl6
    /* 8004BEB0 */ .space 0x04

nonmatching D_8004BEB4_ovl6, 0xC

dlabel D_8004BEB4_ovl6
    /* 8004BEB4 */ .space 0x0C

nonmatching D_8004BEC0_ovl6, 0x10

dlabel D_8004BEC0_ovl6
    /* 8004BEC0 */ .space 0x10

nonmatching D_8004BED0_ovl6, 0x4

dlabel D_8004BED0_ovl6
    /* 8004BED0 */ .space 0x04

nonmatching D_8004BED4_ovl6, 0xC

dlabel D_8004BED4_ovl6
    /* 8004BED4 */ .space 0x0C

nonmatching D_8004BEE0_ovl6, 0x4

dlabel D_8004BEE0_ovl6
    /* 8004BEE0 */ .space 0x04

nonmatching D_8004BEE4_ovl6, 0xC

dlabel D_8004BEE4_ovl6
    /* 8004BEE4 */ .space 0x0C

nonmatching D_8004BEF0_ovl6, 0x4

dlabel D_8004BEF0_ovl6
    /* 8004BEF0 */ .space 0x04

nonmatching D_8004BEF4_ovl6, 0xC

dlabel D_8004BEF4_ovl6
    /* 8004BEF4 */ .space 0x0C

nonmatching D_8004BF00_ovl6, 0x24

dlabel D_8004BF00_ovl6
    /* 8004BF00 */ .space 0x24

nonmatching D_8004BF24_ovl6, 0x4

dlabel D_8004BF24_ovl6
    /* 8004BF24 */ .space 0x04

nonmatching D_8004BF28_ovl6, 0x4

dlabel D_8004BF28_ovl6
    /* 8004BF28 */ .space 0x04

nonmatching D_8004BF2C_ovl6, 0x4

dlabel D_8004BF2C_ovl6
    /* 8004BF2C */ .space 0x04

nonmatching D_8004BF30_ovl6, 0x3

dlabel D_8004BF30_ovl6
    /* 8004BF30 */ .space 0x03

nonmatching D_8004BF33_ovl6, 0x2

dlabel D_8004BF33_ovl6
    /* 8004BF33 */ .space 0x02

nonmatching D_8004BF35_ovl6, 0x1

dlabel D_8004BF35_ovl6
    /* 8004BF35 */ .space 0x01

nonmatching D_8004BF36_ovl6, 0x1

dlabel D_8004BF36_ovl6
    /* 8004BF36 */ .space 0x01

nonmatching D_8004BF37_ovl6, 0x2

dlabel D_8004BF37_ovl6
    /* 8004BF37 */ .space 0x02

nonmatching D_8004BF39_ovl6, 0x1

dlabel D_8004BF39_ovl6
    /* 8004BF39 */ .space 0x01

nonmatching D_8004BF3A_ovl6, 0x1

dlabel D_8004BF3A_ovl6
    /* 8004BF3A */ .space 0x01

nonmatching D_8004BF3B_ovl6, 0x2

dlabel D_8004BF3B_ovl6
    /* 8004BF3B */ .space 0x02

nonmatching D_8004BF3D_ovl6, 0x1

dlabel D_8004BF3D_ovl6
    /* 8004BF3D */ .space 0x01

nonmatching D_8004BF3E_ovl6, 0x1

dlabel D_8004BF3E_ovl6
    /* 8004BF3E */ .space 0x01

nonmatching D_8004BF3F_ovl6, 0x2

dlabel D_8004BF3F_ovl6
    /* 8004BF3F */ .space 0x02

nonmatching D_8004BF41_ovl6, 0x1

dlabel D_8004BF41_ovl6
    /* 8004BF41 */ .space 0x01

nonmatching D_8004BF42_ovl6, 0x2

dlabel D_8004BF42_ovl6
    /* 8004BF42 */ .space 0x02

nonmatching D_8004BF44_ovl6, 0x214

dlabel D_8004BF44_ovl6
    /* 8004BF44 */ .space 0x214

nonmatching D_8004C158_ovl6, 0x4

dlabel D_8004C158_ovl6
    /* 8004C158 */ .space 0x04

nonmatching D_8004C15C_ovl6, 0x4

dlabel D_8004C15C_ovl6
    /* 8004C15C */ .space 0x04

nonmatching D_8004C160_ovl6, 0x2

dlabel D_8004C160_ovl6
    /* 8004C160 */ .space 0x02

nonmatching D_8004C162_ovl6, 0x3

dlabel D_8004C162_ovl6
    /* 8004C162 */ .space 0x03

nonmatching D_8004C165_ovl6, 0x1

dlabel D_8004C165_ovl6
    /* 8004C165 */ .space 0x01

nonmatching D_8004C166_ovl6, 0x1

dlabel D_8004C166_ovl6
    /* 8004C166 */ .space 0x01

nonmatching D_8004C167_ovl6, 0x1

dlabel D_8004C167_ovl6
    /* 8004C167 */ .space 0x01

nonmatching D_8004C168_ovl6, 0x2EC

dlabel D_8004C168_ovl6
    /* 8004C168 */ .space 0x2EC

nonmatching D_8004C454_ovl6, 0x4

dlabel D_8004C454_ovl6
    /* 8004C454 */ .space 0x04

nonmatching D_8004C458_ovl6, 0x4

dlabel D_8004C458_ovl6
    /* 8004C458 */ .space 0x04

nonmatching D_8004C45C_ovl6, 0x4

dlabel D_8004C45C_ovl6
    /* 8004C45C */ .space 0x04

nonmatching D_8004C460_ovl6, 0x10

dlabel D_8004C460_ovl6
    /* 8004C460 */ .space 0x10

nonmatching D_8004C470_ovl6, 0x94

dlabel D_8004C470_ovl6
    /* 8004C470 */ .space 0x94

nonmatching D_8004C504_ovl6, 0x4

dlabel D_8004C504_ovl6
    /* 8004C504 */ .space 0x04

nonmatching D_8004C508_ovl6, 0x4

dlabel D_8004C508_ovl6
    /* 8004C508 */ .space 0x04

nonmatching D_8004C50C_ovl6, 0x18

dlabel D_8004C50C_ovl6
    /* 8004C50C */ .space 0x18

nonmatching D_8004C524_ovl6, 0x4

dlabel D_8004C524_ovl6
    /* 8004C524 */ .space 0x04

nonmatching D_8004C528_ovl6, 0x8

dlabel D_8004C528_ovl6
    /* 8004C528 */ .space 0x08

nonmatching D_8004C530_ovl6, 0x4

dlabel D_8004C530_ovl6
    /* 8004C530 */ .space 0x04

nonmatching D_8004C534_ovl6, 0xC

dlabel D_8004C534_ovl6
    /* 8004C534 */ .space 0x0C
